import { prisma } from "@/lib/prisma";
import { toggleCustomerBlock, updateCustomer } from "./actions";
export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("fa-IR").format(value);
const skinLabels: Record<string,string> = { OILY:"چرب", DRY:"خشک", COMBINATION:"مختلط", NORMAL:"نرمال", SENSITIVE:"حساس", UNKNOWN:"نامشخص" };

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; success?: string; error?: string }> }) {
  const query = await searchParams;
  const customers = await prisma.user.findMany({ where: { role: "CUSTOMER", ...(query.status === "blocked" ? { blockedAt: { not: null } } : query.status === "active" ? { blockedAt: null } : {}), ...(query.q ? { OR: [{ phone: { contains: query.q } }, { displayName: { contains: query.q, mode: "insensitive" } }] } : {}) }, include: { orders: { select: { id: true, total: true, status: true, createdAt: true }, orderBy: { createdAt: "desc" } }, beautyProfiles: { select: { skinType: true, label: true }, take: 2, orderBy: { updatedAt: "desc" } }, reviews: { select: { id: true, status: true } }, favorites: { select: { product: { select: { title: true } } }, take: 4, orderBy: { createdAt: "desc" } } }, orderBy: { createdAt: "desc" }, take: 100 });
  const totalRevenue = customers.reduce((sum, user) => sum + user.orders.filter((order) => !["DRAFT","PENDING_PAYMENT","CANCELLED","REFUNDED"].includes(order.status)).reduce((value, order) => value + order.total, 0), 0);
  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">شناخت مشتری</p><h1>مشتریان</h1><p>سابقه خرید و علاقه هر مشتری را ببین، برای پیگیری یادداشت بگذار و دسترسی حساب را مدیریت کن.</p></div></header><section className="admin-help-note"><strong>مسدودسازی چه زمانی استفاده شود؟</strong><p>فقط برای سوءاستفاده، سفارش‌های غیرواقعی یا درخواست خود مشتری. مشتری مسدودشده نمی‌تواند کد ورود بگیرد؛ اطلاعات سفارش او حذف نمی‌شود.</p></section>
    {query.success ? <div className="admin-alert success">اطلاعات مشتری با موفقیت به‌روزرسانی شد.</div> : null}{query.error ? <div className="admin-alert error">مشتری پیدا نشد یا عملیات انجام نشد.</div> : null}
    <section className="customer-admin-stats"><article><span>مشتریان نتیجه</span><strong>{money(customers.length)}</strong></article><article><span>مشتری فعال</span><strong>{money(customers.filter((item) => !item.blockedAt).length)}</strong></article><article><span>فروش قطعی این گروه</span><strong>{money(totalRevenue)} <small>تومان</small></strong></article></section>
    <form className="customer-search" method="get"><input name="q" defaultValue={query.q} placeholder="نام یا شماره موبایل" /><select name="status" defaultValue={query.status || "all"}><option value="all">همه مشتریان</option><option value="active">فقط فعال</option><option value="blocked">فقط مسدود</option></select><button>جست‌وجو</button>{query.q || (query.status && query.status !== "all") ? <a href="/admin/customers">پاک‌کردن فیلتر</a> : null}</form>
    <section className="customer-admin-list">{customers.length ? customers.map((customer) => { const paidOrders = customer.orders.filter((order) => !["DRAFT","PENDING_PAYMENT","CANCELLED","REFUNDED"].includes(order.status)); const spent = paidOrders.reduce((sum, order) => sum + order.total, 0); return <article key={customer.id}><header><div className="customer-avatar">{customer.displayName?.charAt(0) || "ک"}</div><div><h2>{customer.displayName || "مشتری بدون نام"}</h2><span dir="ltr">{customer.phone || "بدون شماره"}</span></div><span className={`admin-status ${customer.blockedAt ? "archived" : "active"}`}>{customer.blockedAt ? "مسدود" : "فعال"}</span></header><div className="customer-metrics"><div><span>کل سفارش</span><strong>{money(customer.orders.length)}</strong></div><div><span>خرید قطعی</span><strong>{money(paidOrders.length)}</strong></div><div><span>مجموع خرید</span><strong>{money(spent)} تومان</strong></div><div><span>نظر ثبت‌شده</span><strong>{money(customer.reviews.length)}</strong></div></div><div className="customer-insights"><div><h3>شناخت مشتری</h3><p>عضویت: {new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium" }).format(customer.createdAt)}</p><p>پوست: {customer.beautyProfiles.map((profile) => skinLabels[profile.skinType]).join("، ") || "پروفایل ندارد"}</p><p>علاقه‌مندی: {customer.favorites.map((item) => item.product.title).join("، ") || "ثبت نشده"}</p></div><div><h3>آخرین سفارش‌ها</h3>{customer.orders.slice(0,3).map((order) => <p key={order.id}>#{order.id.slice(-6)} · {money(order.total)} تومان · {new Intl.DateTimeFormat("fa-IR").format(order.createdAt)}</p>)}{!customer.orders.length ? <p>هنوز سفارشی ندارد.</p> : null}</div></div><details><summary>یادداشت و برچسب مدیر</summary><form action={updateCustomer} className="customer-note-form"><input type="hidden" name="userId" value={customer.id} /><label>برچسب‌ها<input name="customerTags" defaultValue={customer.customerTags.join("، ")} placeholder="VIP، پیگیری شود، مشتری جدید" /><small>برچسب‌ها را با ویرگول جدا کن.</small></label><label>یادداشت داخلی<textarea name="customerNote" rows={3} defaultValue={customer.customerNote || ""} placeholder="این متن فقط برای مدیران قابل مشاهده است." /></label><button>ذخیره یادداشت</button></form></details>{customer.customerTags.length ? <div className="customer-tags">{customer.customerTags.map((tag) => <span key={tag}>{tag}</span>)}</div> : null}<footer>{customer.customerNote ? <p><strong>یادداشت مدیر:</strong> {customer.customerNote}</p> : <span /> }<form action={toggleCustomerBlock}><input type="hidden" name="userId" value={customer.id} /><button className={customer.blockedAt ? "activate" : "block"}>{customer.blockedAt ? "فعال‌کردن حساب" : "مسدودکردن حساب"}</button></form></footer></article>; }) : <div className="admin-empty"><strong>مشتری‌ای با این مشخصات پیدا نشد.</strong><p>عبارت جست‌وجو یا فیلتر وضعیت را تغییر بده.</p></div>}</section>
  </main>;
}
