ALTER TABLE "HomePageSettings"
ADD COLUMN "newProductsMode" TEXT NOT NULL DEFAULT 'AUTO',
ADD COLUMN "newProductsLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "newProductsLink" TEXT NOT NULL DEFAULT '/products?sort=newest',
ADD COLUMN "newProductsProductIds" JSONB,
ADD COLUMN "bestSellersMode" TEXT NOT NULL DEFAULT 'AUTO',
ADD COLUMN "bestSellersLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "bestSellersLink" TEXT NOT NULL DEFAULT '/products?sort=popular',
ADD COLUMN "bestSellersProductIds" JSONB,
ADD COLUMN "trendingEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "trendingTitle" TEXT NOT NULL DEFAULT 'ترند این روزها',
ADD COLUMN "trendingDescription" TEXT,
ADD COLUMN "trendingLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "trendingLink" TEXT NOT NULL DEFAULT '/products',
ADD COLUMN "editorsEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "editorsTitle" TEXT NOT NULL DEFAULT 'انتخاب ادیتور',
ADD COLUMN "editorsDescription" TEXT,
ADD COLUMN "editorsLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "editorsLink" TEXT NOT NULL DEFAULT '/products',
ADD COLUMN "editorsProductIds" JSONB;
