import Image from "next/image";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma";
import { addToCart } from "@/app/cart/actions";
import { clearCompare, toggleCompare } from "@/app/products/product-actions";
import { COMPARE_COOKIE } from "@/lib/compare";

export const dynamic = "force-dynamic";
const formatPrice = (value: number) => new Intl.NumberFormat("fa-IR").format(value);
const yesNo = (value: boolean | null) => value === true ? "بله" : value === false ? "خیر" : "نامشخص";
const skinLabels: Record<string, string> = { OILY: "چرب", DRY: "خشک", COMBINATION: "مختلط", NORMAL: "نرمال", SENSITIVE: "حساس", UNKNOWN: "نامشخص" };

export default async function ComparePage() {
  const ids = ((await cookies()).get(COMPARE_COOKIE)?.value || "").split(",").filter(Boolean).slice(0, 4);
  const unordered = ids.length ? await prisma.product.findMany({ where: { id: { in: ids }, status: "ACTIVE" }, include: { brand: true, category: true, media: { take: 1, orderBy: { sortOrder: "asc" } }, ingredients: { take: 5, include: { ingredient: true }, orderBy: { position: "asc" } }, skinSuitability: { where: { score: { gt: 0 } }, orderBy: { score: "desc" } }, reviews: { where: { status: "APPROVED" }, select: { rating: true } } } }) : [];
  const products = ids.map((id) => unordered.find((product) => product.id === id)).filter((item): item is NonNullable<typeof item> => Boolean(item));
  return <main className="home-shell compare-page"><section className="compact-hero results-header"><div className="hero-content"><p className="eyebrow">انتخاب مطمئن‌تر</p><h1>مقایسه محصولات</h1><p className="hero-copy">تفاوت قیمت، سازگاری پوست، ترکیبات و تجربه خریداران را کنار هم ببین.</p></div></section>
    {products.length ? <><div className="compare-toolbar"><span>{formatPrice(products.length)} از ۴ محصول انتخاب شده</span><div><a href="/products">افزودن محصول دیگر</a><form action={clearCompare}><button>پاک‌کردن مقایسه</button></form></div></div><div className="compare-scroll"><table className="compare-table"><thead><tr><th>ویژگی</th>{products.map((product) => <th key={product.id}>{product.media[0] ? <Image src={product.media[0].url} alt={product.title} width={150} height={150} /> : <span className="compare-no-image" />}<a href={`/products/${product.slug}`}>{product.title}</a><small>{product.brand.name}</small><form action={toggleCompare}><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="returnTo" value="/compare" /><button>حذف از مقایسه</button></form></th>)}</tr></thead><tbody><tr><th>قیمت</th>{products.map((product) => <td key={product.id}><strong>{formatPrice(product.price)} تومان</strong></td>)}</tr><tr><th>دسته‌بندی</th>{products.map((product) => <td key={product.id}>{product.category.title}</td>)}</tr><tr><th>نوع پوست مناسب</th>{products.map((product) => <td key={product.id}>{product.skinSuitability.length ? product.skinSuitability.map((item) => skinLabels[item.skinType]).join("، ") : "داده کافی نداریم"}</td>)}</tr><tr><th>بدون عطر</th>{products.map((product) => <td key={product.id}>{yesNo(product.fragranceFree)}</td>)}</tr><tr><th>بدون الکل</th>{products.map((product) => <td key={product.id}>{yesNo(product.alcoholFree)}</td>)}</tr><tr><th>ترکیبات کلیدی</th>{products.map((product) => <td key={product.id}>{product.ingredients.length ? product.ingredients.map((item) => item.ingredient.name).join("، ") : "ثبت نشده"}</td>)}</tr><tr><th>امتیاز کاربران</th>{products.map((product) => { const avg = product.reviews.length ? product.reviews.reduce((sum, item) => sum + item.rating, 0) / product.reviews.length : 0; return <td key={product.id}>{avg ? `★ ${new Intl.NumberFormat("fa-IR", { maximumFractionDigits: 1 }).format(avg)} از ۵` : "بدون نظر"}</td>; })}</tr><tr><th>خرید</th>{products.map((product) => <td key={product.id}><form action={addToCart}><input type="hidden" name="productId" value={product.id} /><button className="primary-action" disabled={product.stock - product.reservedStock <= 0}>{product.stock - product.reservedStock > 0 ? "افزودن به سبد" : "ناموجود"}</button></form></td>)}</tr></tbody></table></div></> : <section className="empty-state"><h2>هنوز محصولی برای مقایسه انتخاب نشده است.</h2><p>از فروشگاه ۲ تا ۴ محصول را انتخاب کن تا تفاوت آن‌ها را کنار هم ببینی.</p><a href="/products" className="primary-action">انتخاب محصولات</a></section>}
  </main>;
}
