import { getCustomerUser } from "@/lib/auth";
import { redirect } from "next/navigation";
import { requestCustomerOtp, verifyCustomerOtp } from "./actions";

const errors: Record<string, string> = { phone: "شماره موبایل معتبر وارد کن.", wait: "کد قبلی تازه ارسال شده؛ یک دقیقه بعد دوباره تلاش کن.", sms: "ارسال پیامک هنوز برای محیط واقعی تنظیم نشده است.", expired: "کد منقضی شده؛ کد جدید بگیر.", attempts: "تعداد تلاش بیش از حد مجاز است؛ کد جدید بگیر.", code: "کد واردشده صحیح نیست.", blocked: "این حساب غیرفعال شده است؛ برای بررسی با پشتیبانی تماس بگیر." };

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ step?: string; phone?: string; next?: string; devCode?: string; error?: string }> }) {
  const query = await searchParams;
  if (await getCustomerUser()) redirect(query.next || "/account");
  const verify = query.step === "verify" && query.phone;
  return <main className="customer-login-page"><section className="customer-login-card"><a href="/" className="brand-mark"><span className="brand-symbol">B</span><span className="brand-copy"><strong>BeautyOS</strong><small>حساب شخصی من</small></span></a><div><p className="eyebrow">ورود امن با موبایل</p><h1>{verify ? "کد تأیید را وارد کن" : "ورود یا ساخت حساب"}</h1><p>{verify ? `کد ۶ رقمی برای ${query.phone} ساخته شد.` : "سفارش‌ها، رسیدها و وضعیت ارسال را با شماره موبایلت دنبال کن."}</p></div>{query.error ? <div className="cart-message error">{errors[query.error] || "ورود انجام نشد."}</div> : null}{query.devCode ? <div className="dev-otp"><span>کد تست محلی</span><strong>{query.devCode}</strong><small>در نسخه واقعی این کد پیامک می‌شود.</small></div> : null}{verify ? <form action={verifyCustomerOtp}><input type="hidden" name="phone" value={query.phone} /><input type="hidden" name="next" value={query.next || "/account"} /><label>کد تأیید<input name="code" required inputMode="numeric" maxLength={6} dir="ltr" autoFocus placeholder="------" /></label><button className="primary-action" type="submit">تأیید و ورود</button><a href={`/login?next=${encodeURIComponent(query.next || "/account")}`}>تغییر شماره یا دریافت کد جدید</a></form> : <form action={requestCustomerOtp}><input type="hidden" name="next" value={query.next || "/account"} /><label>شماره موبایل<input name="phone" required inputMode="tel" dir="ltr" placeholder="09123456789" autoFocus /></label><button className="primary-action" type="submit">دریافت کد ورود</button></form>}<small className="login-privacy">با ورود، فقط اطلاعات لازم برای سفارش‌ها و Beauty Passport نگهداری می‌شود.</small></section><aside><span>Beauty Passport + خرید هوشمند</span><h2>همه انتخاب‌ها و سفارش‌هایت در یک حساب.</h2><p>بدون رمز عبور؛ فقط با شماره موبایل و یک کد یک‌بارمصرف.</p></aside></main>;
}
