"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";

const read=(data:FormData,key:string)=>String(data.get(key)||"").trim();
const optional=(data:FormData,key:string)=>read(data,key)||null;
const enabled=(data:FormData,key:string)=>data.get(key)==="on";
const number=(data:FormData,key:string,min:number,max:number,fallback:number)=>{const value=Number(read(data,key));return Number.isFinite(value)?Math.min(max,Math.max(min,Math.round(value))):fallback;};
const oneOf=(data:FormData,key:string,values:string[],fallback:string)=>values.includes(read(data,key))?read(data,key):fallback;
const date=(data:FormData,key:string)=>{const value=optional(data,key);if(!value)return null;const result=new Date(value);return Number.isNaN(result.getTime())?null:result;};
const ids=(data:FormData,key:string)=>data.getAll(key).map(String).filter(Boolean).slice(0,30);
function url(data:FormData,key:string,required=false){const result=optional(data,key);if(!result&&!required)return null;if(result&&(result.startsWith("/")||/^https?:\/\//i.test(result)))return result;throw new Error("INVALID_URL");}

export async function saveHomepage(formData:FormData){
  await requireAdmin();
  const requiredFields=["heroInternalName","heroTitle","newProductsTitle","bestSellersTitle","needsTitle","passportTitle","passportButtonText","posterOneTitle","posterOneButtonText","posterTwoTitle","posterTwoButtonText"];
  if(requiredFields.some((key)=>!read(formData,key)))redirect("/admin/homepage?error=required");
  const heroMediaType=oneOf(formData,"heroMediaType",["IMAGE","VIDEO"],"IMAGE");
  const heroEnabled=enabled(formData,"heroEnabled");
  const heroDesktopImageUrl=url(formData,"heroDesktopImageUrl");
  const heroVideoUrl=url(formData,"heroVideoUrl");
  const heroPosterUrl=url(formData,"heroPosterUrl");
  if(heroEnabled&&((heroMediaType==="IMAGE"&&!heroDesktopImageUrl)||(heroMediaType==="VIDEO"&&(!heroVideoUrl||!heroPosterUrl))))redirect("/admin/homepage?error=media");
  const start=date(formData,"heroStartDate"),end=date(formData,"heroEndDate");
  if(start&&end&&end<=start)redirect("/admin/homepage?error=schedule");
  try{
    const settings={
      heroInternalName:read(formData,"heroInternalName"),heroEnabled,heroMediaType,heroDesktopImageUrl,heroMobileImageUrl:url(formData,"heroMobileImageUrl"),heroImageAlt:optional(formData,"heroImageAlt"),heroVideoUrl,heroMobileVideoUrl:url(formData,"heroMobileVideoUrl"),heroPosterUrl,heroMobilePosterUrl:url(formData,"heroMobilePosterUrl"),heroMediaFit:oneOf(formData,"heroMediaFit",["COVER","CONTAIN"],"COVER"),heroMediaPosition:oneOf(formData,"heroMediaPosition",["CENTER","TOP","BOTTOM","LEFT","RIGHT","CUSTOM"],"CENTER"),heroCustomPosition:optional(formData,"heroCustomPosition"),heroTextPosition:oneOf(formData,"heroTextPosition",["TOP_RIGHT","CENTER_RIGHT","BOTTOM_RIGHT","CENTER","TOP_LEFT","CENTER_LEFT","BOTTOM_LEFT"],"CENTER_RIGHT"),heroTextTheme:oneOf(formData,"heroTextTheme",["LIGHT","DARK"],"LIGHT"),heroOverlayEnabled:enabled(formData,"heroOverlayEnabled"),heroOverlayStrength:number(formData,"heroOverlayStrength",0,50,20),heroEyebrow:read(formData,"heroEyebrow"),heroTitle:read(formData,"heroTitle"),heroDescription:optional(formData,"heroDescription"),heroButtonText:read(formData,"heroButtonText"),heroButtonLink:url(formData,"heroButtonLink",enabled(formData,"heroPrimaryEnabled"))||"/products",heroPrimaryEnabled:enabled(formData,"heroPrimaryEnabled"),heroSecondaryText:optional(formData,"heroSecondaryText"),heroSecondaryLink:url(formData,"heroSecondaryLink",enabled(formData,"heroSecondaryEnabled")),heroSecondaryEnabled:enabled(formData,"heroSecondaryEnabled"),heroStartDate:start,heroEndDate:end,heroSortOrder:number(formData,"heroSortOrder",0,999,0),
      postersEnabled:enabled(formData,"postersEnabled"),posterOneEnabled:enabled(formData,"posterOneEnabled"),posterOneImageUrl:url(formData,"posterOneImageUrl"),posterOneMobileImageUrl:url(formData,"posterOneMobileImageUrl"),posterOneAlt:optional(formData,"posterOneAlt"),posterOneKicker:optional(formData,"posterOneKicker"),posterOneTitle:read(formData,"posterOneTitle"),posterOneDescription:optional(formData,"posterOneDescription"),posterOneButtonText:read(formData,"posterOneButtonText"),posterOneLink:url(formData,"posterOneLink",true)!,posterOneTextPosition:oneOf(formData,"posterOneTextPosition",["TOP_RIGHT","CENTER_RIGHT","BOTTOM_RIGHT","CENTER","TOP_LEFT","CENTER_LEFT","BOTTOM_LEFT"],"BOTTOM_RIGHT"),posterOneTextTheme:oneOf(formData,"posterOneTextTheme",["LIGHT","DARK"],"LIGHT"),posterOneOverlayEnabled:enabled(formData,"posterOneOverlayEnabled"),posterOneOverlayStrength:number(formData,"posterOneOverlayStrength",0,50,25),posterTwoEnabled:enabled(formData,"posterTwoEnabled"),posterTwoImageUrl:url(formData,"posterTwoImageUrl"),posterTwoMobileImageUrl:url(formData,"posterTwoMobileImageUrl"),posterTwoAlt:optional(formData,"posterTwoAlt"),posterTwoKicker:optional(formData,"posterTwoKicker"),posterTwoTitle:read(formData,"posterTwoTitle"),posterTwoDescription:optional(formData,"posterTwoDescription"),posterTwoButtonText:read(formData,"posterTwoButtonText"),posterTwoLink:url(formData,"posterTwoLink",true)!,posterTwoTextPosition:oneOf(formData,"posterTwoTextPosition",["TOP_RIGHT","CENTER_RIGHT","BOTTOM_RIGHT","CENTER","TOP_LEFT","CENTER_LEFT","BOTTOM_LEFT"],"BOTTOM_RIGHT"),posterTwoTextTheme:oneOf(formData,"posterTwoTextTheme",["LIGHT","DARK"],"LIGHT"),posterTwoOverlayEnabled:enabled(formData,"posterTwoOverlayEnabled"),posterTwoOverlayStrength:number(formData,"posterTwoOverlayStrength",0,50,25),
      newProductsEnabled:enabled(formData,"newProductsEnabled"),newProductsTitle:read(formData,"newProductsTitle"),newProductsDescription:optional(formData,"newProductsDescription"),newProductsMode:oneOf(formData,"newProductsMode",["AUTO","MANUAL"],"AUTO"),newProductsLimit:number(formData,"newProductsLimit",4,20,10),newProductsLink:url(formData,"newProductsLink",true)!,newProductsProductIds:ids(formData,"newProductsProductIds"),bestSellersEnabled:enabled(formData,"bestSellersEnabled"),bestSellersTitle:read(formData,"bestSellersTitle"),bestSellersDescription:optional(formData,"bestSellersDescription"),bestSellersMode:oneOf(formData,"bestSellersMode",["AUTO","MANUAL"],"AUTO"),bestSellersLimit:number(formData,"bestSellersLimit",4,20,10),bestSellersLink:url(formData,"bestSellersLink",true)!,bestSellersProductIds:ids(formData,"bestSellersProductIds"),trendingEnabled:enabled(formData,"trendingEnabled"),trendingTitle:read(formData,"trendingTitle"),trendingDescription:optional(formData,"trendingDescription"),trendingLimit:number(formData,"trendingLimit",4,20,10),trendingLink:url(formData,"trendingLink",true)!,editorsEnabled:enabled(formData,"editorsEnabled"),editorsTitle:read(formData,"editorsTitle"),editorsDescription:optional(formData,"editorsDescription"),editorsLimit:number(formData,"editorsLimit",4,20,10),editorsLink:url(formData,"editorsLink",true)!,editorsProductIds:ids(formData,"editorsProductIds"),needsEnabled:enabled(formData,"needsEnabled"),needsTitle:read(formData,"needsTitle"),needsDescription:optional(formData,"needsDescription"),passportEnabled:enabled(formData,"passportEnabled"),passportEyebrow:read(formData,"passportEyebrow"),passportTitle:read(formData,"passportTitle"),passportDescription:optional(formData,"passportDescription"),passportButtonText:read(formData,"passportButtonText"),passportButtonLink:url(formData,"passportButtonLink",true)!
    };
    await prisma.homePageSettings.upsert({where:{id:"default"},update:settings,create:{id:"default",...settings}});
  }catch(error){if(error instanceof Error&&error.message==="INVALID_URL")redirect("/admin/homepage?error=url");throw error;}
  revalidatePath("/");revalidatePath("/admin/homepage");redirect("/admin/homepage?success=saved");
}
