"use client";

import { useState, type CSSProperties, type ChangeEvent } from "react";

type Asset = { id:string; url:string; kind:string; alt:string|null };
type Home = Record<string, string | number | boolean | null>;
const positions = [["TOP_RIGHT","بالا راست"],["CENTER_RIGHT","وسط راست"],["BOTTOM_RIGHT","پایین راست"],["CENTER","وسط"],["TOP_LEFT","بالا چپ"],["CENTER_LEFT","وسط چپ"],["BOTTOM_LEFT","پایین چپ"]];
const mediaPositions = [["CENTER","وسط"],["TOP","بالا"],["BOTTOM","پایین"],["LEFT","چپ"],["RIGHT","راست"],["CUSTOM","موقعیت سفارشی"]];
const text = (home:Home,key:string) => String(home[key] ?? "");
const bool = (home:Home,key:string) => Boolean(home[key]);
const dateValue = (value:unknown) => value ? new Date(String(value)).toISOString().slice(0,16) : "";

export function HomepageCampaignEditor({ home, assets }: { home:Home; assets:Asset[] }) {
  const [mediaType,setMediaType] = useState(text(home,"heroMediaType") || "VIDEO");
  const [values,setValues] = useState<Record<string,string>>({heroDesktopImageUrl:text(home,"heroDesktopImageUrl"),heroMobileImageUrl:text(home,"heroMobileImageUrl"),heroVideoUrl:text(home,"heroVideoUrl"),heroMobileVideoUrl:text(home,"heroMobileVideoUrl"),heroPosterUrl:text(home,"heroPosterUrl"),heroMobilePosterUrl:text(home,"heroMobilePosterUrl"),heroTitle:text(home,"heroTitle"),heroEyebrow:text(home,"heroEyebrow"),heroDescription:text(home,"heroDescription"),heroTextPosition:text(home,"heroTextPosition"),heroTextTheme:text(home,"heroTextTheme"),heroOverlayStrength:text(home,"heroOverlayStrength"),posterOneImageUrl:text(home,"posterOneImageUrl"),posterOneMobileImageUrl:text(home,"posterOneMobileImageUrl"),posterTwoImageUrl:text(home,"posterTwoImageUrl"),posterTwoMobileImageUrl:text(home,"posterTwoMobileImageUrl")});
  const [target,setTarget] = useState(mediaType === "VIDEO" ? "heroVideoUrl" : "heroDesktopImageUrl");
  const update = (event:ChangeEvent<HTMLDivElement>) => { const element=event.target as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement; if(element.name) setValues((current)=>({...current,[element.name]:element.value})); };
  const choose = (url:string) => { const input=document.querySelector<HTMLInputElement>(`[name="${target}"]`); if(input){input.value=url;input.dispatchEvent(new Event("input",{bubbles:true}));setValues((current)=>({...current,[target]:url}));} };
  const previewMedia = mediaType === "VIDEO" ? values.heroPosterUrl || values.heroDesktopImageUrl : values.heroDesktopImageUrl;
  return <div onChange={update} className="campaign-editor">
    <section className="homepage-media-picker"><header><div><strong>کتابخانه رسانه متصل</strong><p>ابتدا مقصد را انتخاب کن، سپس روی فایل موردنظر بزن.</p></div><a href="/admin/media">آپلود / حذف / جایگزینی فایل</a></header><label>استفاده در<select value={target} onChange={(event)=>setTarget(event.target.value)}><option value="heroDesktopImageUrl">Hero · تصویر دسکتاپ</option><option value="heroMobileImageUrl">Hero · تصویر موبایل</option><option value="heroVideoUrl">Hero · ویدیوی دسکتاپ</option><option value="heroMobileVideoUrl">Hero · ویدیوی موبایل</option><option value="heroPosterUrl">Hero · Poster دسکتاپ</option><option value="heroMobilePosterUrl">Hero · Poster موبایل</option><option value="posterOneImageUrl">Banner 1 · تصویر دسکتاپ</option><option value="posterOneMobileImageUrl">Banner 1 · تصویر موبایل</option><option value="posterTwoImageUrl">Banner 2 · تصویر دسکتاپ</option><option value="posterTwoMobileImageUrl">Banner 2 · تصویر موبایل</option></select></label>{assets.length?<div className="homepage-media-strip">{assets.map((asset)=><button type="button" key={asset.id} onClick={()=>choose(asset.url)}>{asset.kind==="VIDEO"?<video src={asset.url} muted preload="metadata"/>:<img src={asset.url} alt={asset.alt||"رسانه"}/>}<span>{asset.kind==="VIDEO"?"ویدیو":"تصویر"}</span></button>)}</div>:<p className="media-picker-empty">هنوز رسانه‌ای آپلود نشده است.</p>}</section>

    <section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>Homepage Hero</h2><p>کمپین اصلی بالای صفحه، با رسانه جدا برای دسکتاپ و موبایل.</p></div></div><div className="admin-form-grid"><label>نام داخلی<input name="heroInternalName" defaultValue={text(home,"heroInternalName")}/><small>فقط در پنل مدیریت دیده می‌شود.</small></label><label>نوع رسانه<select name="heroMediaType" value={mediaType} onChange={(event)=>{setMediaType(event.target.value);setTarget(event.target.value==="VIDEO"?"heroVideoUrl":"heroDesktopImageUrl");}}><option value="IMAGE">تصویر</option><option value="VIDEO">ویدیو</option></select></label><label>ترتیب<input name="heroSortOrder" type="number" min="0" defaultValue={text(home,"heroSortOrder")}/></label></div><label className="homepage-toggle"><input type="checkbox" name="heroEnabled" defaultChecked={bool(home,"heroEnabled")}/><span><strong>Hero فعال باشد</strong><small>زمان‌بندی زیر نیز روی نمایش اثر می‌گذارد.</small></span></label>
      {mediaType==="IMAGE"?<div className="admin-form-grid conditional-media-fields"><label className="field-wide">تصویر دسکتاپ<input name="heroDesktopImageUrl" dir="ltr" defaultValue={text(home,"heroDesktopImageUrl")}/><small>پیشنهاد: 2400×1350، WebP/AVIF، کمتر از ۱٫۵MB</small></label><label className="field-wide">تصویر موبایل<input name="heroMobileImageUrl" dir="ltr" defaultValue={text(home,"heroMobileImageUrl")}/><small>پیشنهاد: 1080×1440، سوژه با فضای امن برای متن</small></label><label className="field-wide">Alt Text<input name="heroImageAlt" defaultValue={text(home,"heroImageAlt")}/><small>توصیف کوتاه و واقعی تصویر برای سئو و دسترسی‌پذیری.</small></label></div>:<div className="admin-form-grid conditional-media-fields"><label className="field-wide">ویدیوی دسکتاپ<input name="heroVideoUrl" dir="ltr" defaultValue={text(home,"heroVideoUrl")}/><small>MP4/WebM افقی، پیشنهاد کمتر از ۱۲MB.</small></label><label className="field-wide">ویدیوی موبایل<input name="heroMobileVideoUrl" dir="ltr" defaultValue={text(home,"heroMobileVideoUrl")}/><small>اختیاری؛ اگر خالی باشد Poster موبایل نمایش داده می‌شود و ویدیوی دسکتاپ دانلود نمی‌شود.</small></label><label className="field-wide">Poster دسکتاپ<input name="heroPosterUrl" dir="ltr" defaultValue={text(home,"heroPosterUrl")}/><small>پیشنهاد: 2400×1350؛ قبل از پخش و در خطای ویدیو نمایش داده می‌شود.</small></label><label className="field-wide">Poster موبایل<input name="heroMobilePosterUrl" dir="ltr" defaultValue={text(home,"heroMobilePosterUrl")}/><small>پیشنهاد: 1080×1440؛ ترکیب‌بندی اختصاصی موبایل.</small></label><label className="field-wide">Alt / توضیح Poster<input name="heroImageAlt" defaultValue={text(home,"heroImageAlt")}/></label></div>}
      <div className="admin-form-grid"><label>نحوه نمایش رسانه<select name="heroMediaFit" defaultValue={text(home,"heroMediaFit")}><option value="COVER">Cover · تمام‌صفحه</option><option value="CONTAIN">Contain · نمایش کامل فریم</option></select></label><label>موقعیت رسانه<select name="heroMediaPosition" defaultValue={text(home,"heroMediaPosition")}>{mediaPositions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>موقعیت سفارشی<input name="heroCustomPosition" dir="ltr" defaultValue={text(home,"heroCustomPosition")} placeholder="مثلاً 35% 50%"/></label><label>محل نوشته<select name="heroTextPosition" defaultValue={text(home,"heroTextPosition")}>{positions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>رنگ نوشته<select name="heroTextTheme" defaultValue={text(home,"heroTextTheme")}><option value="LIGHT">روشن · سفید</option><option value="DARK">تیره · سرمه‌ای</option></select></label><label>قدرت Overlay<select name="heroOverlayStrength" defaultValue={text(home,"heroOverlayStrength")}>{[0,10,20,30,40,50].map(n=><option key={n} value={n}>{n}%</option>)}</select></label></div><label className="homepage-toggle"><input type="checkbox" name="heroOverlayEnabled" defaultChecked={bool(home,"heroOverlayEnabled")}/><span><strong>Overlay فعال باشد</strong><small>Gradient ظریف از سمت متن برای خوانایی بهتر.</small></span></label>
      <div className="admin-form-grid"><label>Eyebrow<input name="heroEyebrow" defaultValue={text(home,"heroEyebrow")}/></label><label>عنوان اصلی<input name="heroTitle" required defaultValue={text(home,"heroTitle")}/></label><label className="field-wide">توضیح<textarea name="heroDescription" rows={3} defaultValue={text(home,"heroDescription")}/></label><label>متن دکمه اصلی<input name="heroButtonText" defaultValue={text(home,"heroButtonText")}/></label><label>لینک دکمه اصلی<input name="heroButtonLink" dir="ltr" defaultValue={text(home,"heroButtonLink")}/></label><label>متن دکمه دوم<input name="heroSecondaryText" defaultValue={text(home,"heroSecondaryText")}/></label><label>لینک دکمه دوم<input name="heroSecondaryLink" dir="ltr" defaultValue={text(home,"heroSecondaryLink")}/></label></div><div className="homepage-section-editor"><label className="homepage-toggle"><input type="checkbox" name="heroPrimaryEnabled" defaultChecked={bool(home,"heroPrimaryEnabled")}/><span><strong>دکمه اصلی</strong><small>نمایش CTA اصلی</small></span></label><label className="homepage-toggle"><input type="checkbox" name="heroSecondaryEnabled" defaultChecked={bool(home,"heroSecondaryEnabled")}/><span><strong>دکمه دوم</strong><small>نمایش CTA ثانویه</small></span></label></div><div className="admin-form-grid"><label>شروع نمایش<input name="heroStartDate" type="datetime-local" defaultValue={dateValue(home.heroStartDate)}/></label><label>پایان نمایش<input name="heroEndDate" type="datetime-local" defaultValue={dateValue(home.heroEndDate)}/></label></div>
      <div className={`hero-admin-preview theme-${(values.heroTextTheme||"LIGHT").toLowerCase()}`} style={{"--preview-overlay":Number(values.heroOverlayStrength||20)/100} as CSSProperties}>{previewMedia?<img src={previewMedia} alt="پیش‌نمایش Hero"/>:<span className="preview-empty">رسانه Hero را انتخاب کن</span>}<div className="hero-admin-preview-overlay"/><div><small>{values.heroEyebrow}</small><h3>{values.heroTitle}</h3><p>{values.heroDescription}</p><button type="button">پیش‌نمایش دکمه</button></div></div>
    </section>

    <section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>Homepage Promotional Banners</h2><p>دو Campaign Card تصویری؛ هرکدام مستقل و دارای تصویر موبایل.</p></div></div><label className="homepage-toggle"><input type="checkbox" name="postersEnabled" defaultChecked={bool(home,"postersEnabled")}/><span><strong>بخش Bannerها فعال باشد</strong><small>هر Banner را نیز جداگانه می‌توانی خاموش کنی.</small></span></label><div className="homepage-poster-editor">{["One","Two"].map((word,index)=>{const prefix=`poster${word}`;return <fieldset key={word}><legend>Banner {index+1}</legend><label className="homepage-toggle"><input type="checkbox" name={`${prefix}Enabled`} defaultChecked={bool(home,`${prefix}Enabled`)}/><span><strong>فعال</strong><small>اگر فقط یکی فعال باشد تمام عرض می‌شود.</small></span></label><label>تصویر دسکتاپ<input name={`${prefix}ImageUrl`} dir="ltr" defaultValue={text(home,`${prefix}ImageUrl`)}/><small>پیشنهاد: 1600×2000، نسبت ۴:۵</small></label><label>تصویر موبایل<input name={`${prefix}MobileImageUrl`} dir="ltr" defaultValue={text(home,`${prefix}MobileImageUrl`)}/><small>پیشنهاد: 1080×1350</small></label><label>Alt Text<input name={`${prefix}Alt`} defaultValue={text(home,`${prefix}Alt`)}/></label><label>Eyebrow<input name={`${prefix}Kicker`} defaultValue={text(home,`${prefix}Kicker`)}/></label><label>عنوان<input name={`${prefix}Title`} required defaultValue={text(home,`${prefix}Title`)}/></label><label>توضیح<textarea name={`${prefix}Description`} rows={2} defaultValue={text(home,`${prefix}Description`)}/></label><label>متن دکمه<input name={`${prefix}ButtonText`} required defaultValue={text(home,`${prefix}ButtonText`)}/></label><label>لینک<input name={`${prefix}Link`} dir="ltr" required defaultValue={text(home,`${prefix}Link`)}/></label><label>محل نوشته<select name={`${prefix}TextPosition`} defaultValue={text(home,`${prefix}TextPosition`)}>{positions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>رنگ نوشته<select name={`${prefix}TextTheme`} defaultValue={text(home,`${prefix}TextTheme`)}><option value="LIGHT">روشن</option><option value="DARK">تیره</option></select></label><label>قدرت Overlay<select name={`${prefix}OverlayStrength`} defaultValue={text(home,`${prefix}OverlayStrength`)}>{[0,10,20,30,40,50].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><label className="homepage-toggle"><input type="checkbox" name={`${prefix}OverlayEnabled`} defaultChecked={bool(home,`${prefix}OverlayEnabled`)}/><span><strong>Overlay فعال</strong><small>برای خوانایی متن روی تصویر</small></span></label></fieldset>})}</div></section>
  </div>;
}
