import { getHomeSettings } from "@/lib/home-settings";
import { saveHomepage } from "./actions";
import { prisma } from "@/lib/prisma";
import { HomepageMediaPicker } from "./media-picker";
export const dynamic = "force-dynamic";

const Toggle = ({ name, checked, title, hint }: { name: string; checked: boolean; title: string; hint: string }) => <label className="homepage-toggle"><input type="checkbox" name={name} defaultChecked={checked} /><span><strong>{title}</strong><small>{hint}</small></span></label>;

export default async function HomepageAdmin({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [home, query, assets] = await Promise.all([getHomeSettings(), searchParams, prisma.mediaAsset.findMany({ select:{id:true,url:true,kind:true,alt:true}, orderBy:{createdAt:"desc"}, take:20 })]);
  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">ویترین اصلی فروشگاه</p><h1>مدیریت صفحه اصلی</h1><p>ویدیو، دو پوستر، ردیف محصولات و معرفی پاسپورت را بدون تغییر کد کنترل کن.</p></div><a href="/" className="secondary-action">دیدن صفحه اصلی</a></header>
    <section className="admin-help-note"><strong>پیشنهاد برای بهترین نتیجه:</strong><p>ویدیو افقی MP4 با نسبت ۱۶:۹ و بدون نوشته داخل تصویر استفاده کن. پوسترها بهتر است عمودی یا مربعی و هر دو هم‌اندازه باشند.</p></section>
    <HomepageMediaPicker assets={assets} />
    {query.success ? <div className="admin-alert success">صفحه اصلی ذخیره و منتشر شد.</div> : null}{query.error ? <div className="admin-alert error">{query.error === "url" ? "لینک‌ها باید با https:// یا / شروع شوند." : "فیلدهای ضروری را کامل کن."}</div> : null}
    <form action={saveHomepage} className="admin-product-form homepage-admin-form">
      <section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>بنر ویدیویی اصلی</h2><p>اولین تصویر صفحه؛ بزرگ و تمام‌عرض.</p></div></div><Toggle name="heroEnabled" checked={home.heroEnabled} title="نمایش بنر ویدیویی" hint="با خاموش‌کردن، کل این بخش حذف می‌شود." /><div className="admin-form-grid"><label className="field-wide">آدرس فایل ویدیو<input name="heroVideoUrl" dir="ltr" defaultValue={home.heroVideoUrl || ""} placeholder="/media/hero.mp4 یا https://.../video.mp4" /><small>ویدیو خودکار، بی‌صدا و تکرارشونده پخش می‌شود.</small></label><label className="field-wide">تصویر جایگزین ویدیو<input name="heroPosterUrl" dir="ltr" defaultValue={home.heroPosterUrl || ""} placeholder="/media/hero-poster.jpg" /><small>تا زمان بارگذاری ویدیو نمایش داده می‌شود.</small></label><label>متن کوچک بالای عنوان<input name="heroEyebrow" defaultValue={home.heroEyebrow} /></label><label>عنوان اصلی<input name="heroTitle" required defaultValue={home.heroTitle} /></label><label className="field-wide">توضیح<textarea name="heroDescription" rows={3} defaultValue={home.heroDescription || ""} /></label><label>متن دکمه اصلی<input name="heroButtonText" required defaultValue={home.heroButtonText} /></label><label>لینک دکمه اصلی<input name="heroButtonLink" dir="ltr" required defaultValue={home.heroButtonLink} /></label><label>متن دکمه دوم<input name="heroSecondaryText" defaultValue={home.heroSecondaryText || ""} /></label><label>لینک دکمه دوم<input name="heroSecondaryLink" dir="ltr" defaultValue={home.heroSecondaryLink || ""} /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>دو پوستر کنار هم</h2><p>دو داستان یا مسیر خرید را با تصویر بزرگ معرفی کن.</p></div></div><Toggle name="postersEnabled" checked={home.postersEnabled} title="نمایش پوسترها" hint="هر دو پوستر با هم فعال یا مخفی می‌شوند." /><div className="homepage-poster-editor"><fieldset><legend>پوستر اول</legend><label>تصویر<input name="posterOneImageUrl" dir="ltr" defaultValue={home.posterOneImageUrl || ""} placeholder="/media/poster-1.jpg" /></label><label>برچسب کوچک<input name="posterOneKicker" defaultValue={home.posterOneKicker || ""} /></label><label>عنوان<input name="posterOneTitle" required defaultValue={home.posterOneTitle} /></label><label>توضیح<textarea name="posterOneDescription" rows={2} defaultValue={home.posterOneDescription || ""} /></label><label>متن دکمه<input name="posterOneButtonText" required defaultValue={home.posterOneButtonText} /></label><label>لینک<input name="posterOneLink" dir="ltr" required defaultValue={home.posterOneLink} /></label></fieldset><fieldset><legend>پوستر دوم</legend><label>تصویر<input name="posterTwoImageUrl" dir="ltr" defaultValue={home.posterTwoImageUrl || ""} placeholder="/media/poster-2.jpg" /></label><label>برچسب کوچک<input name="posterTwoKicker" defaultValue={home.posterTwoKicker || ""} /></label><label>عنوان<input name="posterTwoTitle" required defaultValue={home.posterTwoTitle} /></label><label>توضیح<textarea name="posterTwoDescription" rows={2} defaultValue={home.posterTwoDescription || ""} /></label><label>متن دکمه<input name="posterTwoButtonText" required defaultValue={home.posterTwoButtonText} /></label><label>لینک<input name="posterTwoLink" dir="ltr" required defaultValue={home.posterTwoLink} /></label></fieldset></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۳</span><div><h2>ردیف‌های محصول</h2><p>محصولات خودکار از کاتالوگ و سفارش‌های واقعی انتخاب می‌شوند.</p></div></div><div className="homepage-section-editor"><div><Toggle name="newProductsEnabled" checked={home.newProductsEnabled} title="تازه‌رسیده‌ها" hint="جدیدترین محصولات فعال" /><label>عنوان<input name="newProductsTitle" required defaultValue={home.newProductsTitle} /></label><label>توضیح<input name="newProductsDescription" defaultValue={home.newProductsDescription || ""} /></label></div><div><Toggle name="bestSellersEnabled" checked={home.bestSellersEnabled} title="پرفروش‌ها" hint="براساس سفارش‌های موفق" /><label>عنوان<input name="bestSellersTitle" required defaultValue={home.bestSellersTitle} /></label><label>توضیح<input name="bestSellersDescription" defaultValue={home.bestSellersDescription || ""} /></label></div></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۴</span><div><h2>انتخاب براساس نیاز</h2><p>میانبرهایی برای رسیدن به مسئله پوستی مشتری.</p></div></div><Toggle name="needsEnabled" checked={home.needsEnabled} title="نمایش نیازهای پوستی" hint="کارت‌های جوش، خشکی، ضدآفتاب و بودجه" /><div className="admin-form-grid"><label>عنوان<input name="needsTitle" required defaultValue={home.needsTitle} /></label><label>توضیح<input name="needsDescription" defaultValue={home.needsDescription || ""} /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۵</span><div><h2>معرفی Beauty Passport</h2><p>بخش پایانی برای معرفی مزیت اصلی فروشگاه.</p></div></div><Toggle name="passportEnabled" checked={home.passportEnabled} title="نمایش معرفی پاسپورت" hint="با خاموش‌کردن، کل بخش حذف می‌شود." /><div className="admin-form-grid"><label>برچسب کوچک<input name="passportEyebrow" defaultValue={home.passportEyebrow} /></label><label>عنوان<input name="passportTitle" required defaultValue={home.passportTitle} /></label><label className="field-wide">توضیح<textarea name="passportDescription" rows={3} defaultValue={home.passportDescription || ""} /></label><label>متن دکمه<input name="passportButtonText" required defaultValue={home.passportButtonText} /></label><label>لینک دکمه<input name="passportButtonLink" dir="ltr" required defaultValue={home.passportButtonLink} /></label></div></section>
      <div className="admin-form-actions sticky-home-save"><button className="primary-action">ذخیره و انتشار صفحه اصلی</button><a href="/" className="secondary-action">مشاهده خروجی</a></div>
    </form>
  </main>;
}
