import { getSeoSettings } from "@/lib/seo";
import { saveSeoSettings } from "./actions";
export const dynamic = "force-dynamic";

export default async function SeoAdminPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [seo, query] = await Promise.all([getSeoSettings(), searchParams]);
  return <main className="admin-page narrow"><header className="admin-page-header"><div><p className="admin-kicker">دیده‌شدن در گوگل</p><h1>تنظیمات سئو</h1><p>عنوان و توضیح پیش‌فرض سایت، دامنه اصلی و اجازه ایندکس موتورهای جست‌وجو را مدیریت کن.</p></div></header>
    <section className="admin-help-note"><strong>نکته مهم قبل از انتشار:</strong><p>تا وقتی سایت روی دامنه واقعی و نسخه نهایی قرار نگرفته، «اجازه ایندکس» را خاموش نگه دار. بعد از اتصال دامنه آن را روشن و آدرس sitemap.xml را در Google Search Console ثبت کن.</p></section>
    {query.success ? <div className="admin-alert success">تنظیمات سئو ذخیره شد.</div> : null}{query.error ? <div className="admin-alert error">دامنه باید با https:// شروع شود، توضیح حداقل ۵۰ حرف باشد و قالب عنوان شامل %s باشد.</div> : null}
    <form action={saveSeoSettings} className="admin-product-form admin-form-card"><section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>هویت سایت در نتایج</h2><p>این اطلاعات در صفحه‌هایی که عنوان اختصاصی ندارند استفاده می‌شود.</p></div></div><div className="admin-form-grid"><label>نام کوتاه سایت<input name="siteName" defaultValue={seo.siteName} required /></label><label>عنوان پیش‌فرض<input name="defaultTitle" defaultValue={seo.defaultTitle} required /></label><label className="field-wide">توضیح پیش‌فرض<textarea name="defaultDescription" rows={4} defaultValue={seo.defaultDescription} required minLength={50} /><small>حدود ۱۲۰ تا ۱۶۰ کاراکتر و شامل دلیل تفاوت فروشگاه باشد.</small></label><label>قالب عنوان صفحات<input name="titleTemplate" dir="ltr" defaultValue={seo.titleTemplate} required /><small>%s با عنوان هر صفحه جایگزین می‌شود.</small></label><label>نام مجموعه<input name="organizationName" defaultValue={seo.organizationName || ""} /></label></div></section><section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>دامنه و گوگل</h2><p>آدرس‌ها باید به دامنه نهایی سایت اشاره کنند.</p></div></div><div className="admin-form-grid"><label className="field-wide">دامنه اصلی<input name="siteUrl" dir="ltr" defaultValue={seo.siteUrl} placeholder="https://example.com" required /></label><label>آدرس لوگو<input name="logoUrl" dir="ltr" defaultValue={seo.logoUrl || ""} placeholder="/logo.png" /></label><label>کد تأیید Google Search Console<input name="googleVerification" dir="ltr" defaultValue={seo.googleVerification || ""} placeholder="فقط مقدار content" /></label></div><label className="payment-active seo-index-toggle"><input name="allowIndexing" type="checkbox" defaultChecked={seo.allowIndexing} /><span><strong>اجازه نمایش سایت در گوگل</strong><small>فقط بعد از اتصال دامنه واقعی فعال کن.</small></span></label></section><div className="admin-form-actions"><button className="primary-action">ذخیره تنظیمات سئو</button></div></form>
  </main>;
}
