import { prisma } from "@/lib/prisma";
import { createShippingMethod, deleteShippingMethod, updateShippingMethod } from "./actions";

export const dynamic = "force-dynamic";
const formatPrice = (price: number) => new Intl.NumberFormat("fa-IR").format(price);

export default async function ShippingAdminPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const query = await searchParams;
  const methods = await prisma.shippingMethod.findMany({ include: { _count: { select: { orders: true } } }, orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }] });
  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">تنظیمات فروش</p><h1>روش‌ها و هزینه ارسال</h1><p>مشتری در تسویه‌حساب یکی از روش‌های فعال را انتخاب می‌کند و هزینه آن وارد مبلغ نهایی می‌شود.</p></div></header>
    <section className="admin-help-note"><strong>راهنمای ساده:</strong><p>قیمت را به تومان وارد کن. اگر «ارسال رایگان از مبلغ» را پر کنی، برای سفارش‌های بالاتر از آن عدد هزینه ارسال صفر می‌شود. روش غیرفعال به مشتری نمایش داده نمی‌شود.</p></section>
    {query.success ? <div className="admin-alert success">روش ارسال با موفقیت ذخیره شد.</div> : null}{query.error ? <div className="admin-alert error">{query.error === "used" ? "این روش در سفارش‌های قبلی استفاده شده و قابل حذف نیست؛ آن را غیرفعال کن." : "عنوان و اطلاعات روش ارسال را بررسی کن."}</div> : null}
    <div className="shipping-admin-layout"><section className="shipping-create"><div className="admin-form-heading"><span>+</span><div><h2>روش ارسال جدید</h2><p>مثلاً پست پیشتاز، تیپاکس یا پیک شهری</p></div></div><form action={createShippingMethod} className="admin-product-form"><label>عنوان<input name="title" required placeholder="پست پیشتاز" /></label><label>توضیح<input name="description" placeholder="ارسال به سراسر کشور" /></label><div className="admin-form-grid"><label>هزینه (تومان)<input name="price" type="number" min="0" defaultValue="0" /></label><label>ارسال رایگان از مبلغ<input name="freeAbove" type="number" min="0" placeholder="اختیاری" /></label><label>زمان تقریبی<input name="estimatedDays" placeholder="۲ تا ۴ روز کاری" /></label><label>ترتیب نمایش<input name="sortOrder" type="number" min="0" defaultValue="0" /></label></div><label className="payment-active"><input name="active" type="checkbox" defaultChecked /> این روش فعال و قابل انتخاب باشد</label><button type="submit" className="primary-action">افزودن روش ارسال</button></form></section>
      <section className="shipping-method-list"><div className="admin-table-head"><span>روش‌های ثبت‌شده</span><small>{methods.filter((item) => item.active).length} روش فعال</small></div>{methods.map((method) => <article key={method.id}><form action={updateShippingMethod.bind(null, method.id)} className="admin-product-form"><header><div><span className={`admin-status ${method.active ? "active" : "archived"}`}>{method.active ? "فعال" : "غیرفعال"}</span><strong>{method.title}</strong></div><small>{method._count.orders} سفارش</small></header><div className="admin-form-grid"><label>عنوان<input name="title" defaultValue={method.title} required /></label><label>توضیح<input name="description" defaultValue={method.description || ""} /></label><label>هزینه<input name="price" type="number" min="0" defaultValue={method.price} /></label><label>رایگان از مبلغ<input name="freeAbove" type="number" min="0" defaultValue={method.freeAbove || ""} /></label><label>زمان تحویل<input name="estimatedDays" defaultValue={method.estimatedDays || ""} /></label><label>ترتیب<input name="sortOrder" type="number" min="0" defaultValue={method.sortOrder} /></label></div><div className="shipping-method-footer"><label><input name="active" type="checkbox" defaultChecked={method.active} /> فعال</label><span>{method.price === 0 ? "رایگان" : `${formatPrice(method.price)} تومان`}</span><button type="submit">ذخیره تغییرات</button></div></form>{method._count.orders === 0 ? <form action={deleteShippingMethod} className="shipping-delete"><input type="hidden" name="id" value={method.id} /><button type="submit">حذف روش</button></form> : null}</article>)}</section></div>
  </main>;
}
