ALTER TABLE "HomePageSettings"
ADD COLUMN "heroInternalName" TEXT NOT NULL DEFAULT 'کمپین اصلی',
ADD COLUMN "heroMediaType" TEXT NOT NULL DEFAULT 'VIDEO',
ADD COLUMN "heroDesktopImageUrl" TEXT,
ADD COLUMN "heroMobileImageUrl" TEXT,
ADD COLUMN "heroImageAlt" TEXT,
ADD COLUMN "heroMobileVideoUrl" TEXT,
ADD COLUMN "heroMobilePosterUrl" TEXT,
ADD COLUMN "heroMediaFit" TEXT NOT NULL DEFAULT 'COVER',
ADD COLUMN "heroMediaPosition" TEXT NOT NULL DEFAULT 'CENTER',
ADD COLUMN "heroCustomPosition" TEXT,
ADD COLUMN "heroTextPosition" TEXT NOT NULL DEFAULT 'CENTER_RIGHT',
ADD COLUMN "heroTextTheme" TEXT NOT NULL DEFAULT 'LIGHT',
ADD COLUMN "heroOverlayEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "heroOverlayStrength" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "heroPrimaryEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "heroSecondaryEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "heroStartDate" TIMESTAMP(3),
ADD COLUMN "heroEndDate" TIMESTAMP(3),
ADD COLUMN "heroSortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "posterOneEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "posterOneMobileImageUrl" TEXT,
ADD COLUMN "posterOneAlt" TEXT,
ADD COLUMN "posterOneTextPosition" TEXT NOT NULL DEFAULT 'BOTTOM_RIGHT',
ADD COLUMN "posterOneTextTheme" TEXT NOT NULL DEFAULT 'LIGHT',
ADD COLUMN "posterOneOverlayEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "posterOneOverlayStrength" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "posterTwoEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "posterTwoMobileImageUrl" TEXT,
ADD COLUMN "posterTwoAlt" TEXT,
ADD COLUMN "posterTwoTextPosition" TEXT NOT NULL DEFAULT 'BOTTOM_RIGHT',
ADD COLUMN "posterTwoTextTheme" TEXT NOT NULL DEFAULT 'LIGHT',
ADD COLUMN "posterTwoOverlayEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "posterTwoOverlayStrength" INTEGER NOT NULL DEFAULT 25;

UPDATE "HomePageSettings"
SET "heroMediaType" = CASE WHEN "heroVideoUrl" IS NOT NULL THEN 'VIDEO' ELSE 'IMAGE' END,
    "heroDesktopImageUrl" = CASE WHEN "heroVideoUrl" IS NULL THEN "heroPosterUrl" ELSE NULL END,
    "heroImageAlt" = "heroTitle",
    "posterOneAlt" = "posterOneTitle",
    "posterTwoAlt" = "posterTwoTitle";
