import { OrderStatus, Prisma } from "@prisma/client";
import type { CSSProperties } from "react";
import { prisma } from "@/lib/prisma";
import { getHomeSettings } from "@/lib/home-settings";
import { getCustomerUser } from "@/lib/auth";
import { getSeoSettings } from "@/lib/seo";
import { getStoreSettings } from "@/lib/store-settings";
import { HeroMedia } from "./hero-media";
import { ProductCard, type ProductCardData } from "./product-card";

export const dynamic="force-dynamic";
const successful:OrderStatus[]=["PAID","PROCESSING","SHIPPED","DELIVERED"];
const needs=[["پوستم جوش می‌زند","انتخاب‌های سازگارتر با پوست مستعد جوش","جوش و منافذ"],["پوستم خشک است","مراقبت ملایم برای خشکی و کشیدگی","خشکی پوست"],["ضدآفتاب می‌خواهم","محافظت روزانه متناسب با پوست تو","ضدآفتاب"],["روتین ساده می‌خواهم","یک مسیر کوتاه برای صبح و شب","روتین ساده"],["انتخاب اقتصادی","محصولات مؤثر در محدوده بودجه کمتر","محصول اقتصادی"],["نمی‌دانم چی بخرم","با چند سؤال ساده انتخاب را شروع کن","راهنمای خرید"]];
const placement=(value:string)=>value.toLowerCase().replaceAll("_","-");
const productSelect={id:true,slug:true,title:true,subtitle:true,price:true,compareAtPrice:true,stock:true,reservedStock:true,media:{take:2,orderBy:{sortOrder:"asc" as const},select:{url:true,alt:true}},brand:{select:{name:true}},reviews:{where:{status:"APPROVED" as const},select:{rating:true}}} satisfies Prisma.ProductSelect;
const jsonIds=(value:unknown)=>Array.isArray(value)?value.map(String).filter(Boolean):[];
async function productsByIds(ids:string[],limit:number){if(!ids.length)return[];const rows=await prisma.product.findMany({where:{id:{in:ids.slice(0,limit)},status:"ACTIVE"},select:productSelect});const map=new Map(rows.map(row=>[row.id,row]));return ids.map(id=>map.get(id)).filter((row):row is ProductCardData=>Boolean(row)).slice(0,limit);}
const ProductRail=({title,description,href,products,favorites}:{title:string;description?:string|null;href:string;products:ProductCardData[];favorites:Set<string>})=>products.length?<section className="homepage-product-section"><header><div><h2>{title}</h2>{description?<p>{description}</p>:null}</div><a href={href}>مشاهده همه <span aria-hidden="true">←</span></a></header><div className="homepage-product-rail">{products.map(product=><ProductCard key={product.id} product={product} initialFavorite={favorites.has(product.id)} returnTo="/"/>)}</div><div className="product-rail-progress" aria-hidden="true"><span/></div></section>:null;

export default async function HomePage(){
  const [home,customer,seo,store]=await Promise.all([getHomeSettings(),getCustomerUser(),getSeoSettings(),getStoreSettings()]);
  const newIds=jsonIds(home.newProductsProductIds),bestIds=jsonIds(home.bestSellersProductIds),editorIds=jsonIds(home.editorsProductIds);
  const newestPromise=home.newProductsMode==="MANUAL"?productsByIds(newIds,home.newProductsLimit):prisma.product.findMany({where:{status:"ACTIVE"},select:productSelect,orderBy:{createdAt:"desc"},take:home.newProductsLimit});
  const bestPromise=home.bestSellersMode==="MANUAL"?productsByIds(bestIds,home.bestSellersLimit):(async()=>{const grouped=await prisma.orderItem.groupBy({by:["productId"],where:{order:{status:{in:successful}}},_sum:{quantity:true},orderBy:{_sum:{quantity:"desc"}},take:home.bestSellersLimit});return productsByIds(grouped.map(item=>item.productId),home.bestSellersLimit);})();
  const trendingPromise=(async()=>{const grouped=await prisma.favorite.groupBy({by:["productId"],_count:{productId:true},orderBy:{_count:{productId:"desc"}},take:home.trendingLimit});return productsByIds(grouped.map(item=>item.productId),home.trendingLimit);})();
  const [newest,best,trending,editors,favoriteRows]=await Promise.all([newestPromise.catch(()=>[]),bestPromise.catch(()=>[]),trendingPromise.catch(()=>[]),productsByIds(editorIds,home.editorsLimit).catch(()=>[]),customer?prisma.favorite.findMany({where:{userId:customer.id},select:{productId:true}}).catch(()=>[]):Promise.resolve([])]);
  const favoriteIds=new Set(favoriteRows.map(item=>item.productId));
  const now=new Date();const heroVisible=home.heroEnabled&&(!home.heroStartDate||home.heroStartDate<=now)&&(!home.heroEndDate||home.heroEndDate>=now);
  const banners=[{enabled:home.posterOneEnabled,image:home.posterOneImageUrl,mobile:home.posterOneMobileImageUrl,alt:home.posterOneAlt,kicker:home.posterOneKicker,title:home.posterOneTitle,description:home.posterOneDescription,button:home.posterOneButtonText,href:home.posterOneLink,position:home.posterOneTextPosition,theme:home.posterOneTextTheme,overlay:home.posterOneOverlayEnabled,strength:home.posterOneOverlayStrength},{enabled:home.posterTwoEnabled,image:home.posterTwoImageUrl,mobile:home.posterTwoMobileImageUrl,alt:home.posterTwoAlt,kicker:home.posterTwoKicker,title:home.posterTwoTitle,description:home.posterTwoDescription,button:home.posterTwoButtonText,href:home.posterTwoLink,position:home.posterTwoTextPosition,theme:home.posterTwoTextTheme,overlay:home.posterTwoOverlayEnabled,strength:home.posterTwoOverlayStrength}].filter(banner=>banner.enabled);
  const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":`${seo.siteUrl}#organization`,name:seo.organizationName||store.storeName,url:seo.siteUrl,logo:seo.logoUrl||store.logoUrl||undefined},{"@type":"WebSite","@id":`${seo.siteUrl}#website`,url:seo.siteUrl,name:seo.siteName,publisher:{"@id":`${seo.siteUrl}#organization`},potentialAction:{"@type":"SearchAction",target:{"@type":"EntryPoint",urlTemplate:`${seo.siteUrl}/products?q={search_term_string}`},"query-input":"required name=search_term_string"}}]};
  return <main className="luxury-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/>{!heroVisible?<h1 className="sr-only">{seo.defaultTitle}</h1>:null}
    {heroVisible?<section className={`homepage-hero theme-${home.heroTextTheme.toLowerCase()} text-${placement(home.heroTextPosition)}`} style={{"--hero-overlay":home.heroOverlayEnabled?home.heroOverlayStrength/100:0} as CSSProperties}><HeroMedia mediaType={home.heroMediaType} desktopImage={home.heroDesktopImageUrl} mobileImage={home.heroMobileImageUrl} desktopVideo={home.heroVideoUrl} mobileVideo={home.heroMobileVideoUrl} desktopPoster={home.heroPosterUrl} mobilePoster={home.heroMobilePosterUrl} alt={home.heroImageAlt||home.heroTitle} fit={home.heroMediaFit} position={home.heroMediaPosition} customPosition={home.heroCustomPosition}/><div className="homepage-hero-overlay"/><div className="homepage-hero-content"><span>{home.heroEyebrow}</span><h1>{home.heroTitle}</h1>{home.heroDescription?<p>{home.heroDescription}</p>:null}<div>{home.heroPrimaryEnabled&&home.heroButtonText&&home.heroButtonLink?<a className="hero-cta primary" href={home.heroButtonLink} data-analytics="hero_primary">{home.heroButtonText}</a>:null}{home.heroSecondaryEnabled&&home.heroSecondaryText&&home.heroSecondaryLink?<a className="hero-cta secondary" href={home.heroSecondaryLink} data-analytics="hero_secondary">{home.heroSecondaryText}</a>:null}</div></div></section>:null}
    {home.postersEnabled&&banners.length?<section className={`promo-banner-section count-${banners.length}`}>{banners.map((banner,index)=><article key={index} className={`promo-banner theme-${banner.theme.toLowerCase()} text-${placement(banner.position)} ${!banner.image?`poster-placeholder tone-${index+1}`:""}`} style={{"--banner-overlay":banner.overlay?banner.strength/100:0} as CSSProperties}>{banner.image||banner.mobile?<picture><source media="(max-width: 767px)" srcSet={banner.mobile||banner.image||""}/><img src={banner.image||banner.mobile||""} alt={banner.alt||banner.title} loading="lazy" decoding="async"/></picture>:<div className="poster-art"><i/><i/><i/></div>}<div className="promo-banner-overlay"/><div className="promo-banner-copy">{banner.kicker?<span>{banner.kicker}</span>:null}<h2>{banner.title}</h2>{banner.description?<p>{banner.description}</p>:null}<a href={banner.href} data-analytics={`banner_${index+1}`}>{banner.button}<b aria-hidden="true">←</b></a></div></article>)}</section>:null}
    {home.newProductsEnabled?<ProductRail title={home.newProductsTitle} description={home.newProductsDescription} href={home.newProductsLink} products={newest} favorites={favoriteIds}/>:null}
    {home.bestSellersEnabled?<ProductRail title={home.bestSellersTitle} description={home.bestSellersDescription} href={home.bestSellersLink} products={best.length?best:newest.slice(0,home.bestSellersLimit)} favorites={favoriteIds}/>:null}
    {home.trendingEnabled?<ProductRail title={home.trendingTitle} description={home.trendingDescription} href={home.trendingLink} products={trending} favorites={favoriteIds}/>:null}
    {home.editorsEnabled?<ProductRail title={home.editorsTitle} description={home.editorsDescription} href={home.editorsLink} products={editors} favorites={favoriteIds}/>:null}
    {home.needsEnabled?<section className="luxury-needs"><header><h2>{home.needsTitle}</h2>{home.needsDescription?<p>{home.needsDescription}</p>:null}</header><div>{needs.map(([title,description,intent],index)=><a href={`/needs?intent=${encodeURIComponent(intent)}`} key={title}><span>0{index+1}</span><h3>{title}</h3><p>{description}</p><b>شروع ←</b></a>)}</div></section>:null}
    {home.passportEnabled?<section className="passport-editorial"><div className="passport-visual"><span>PERSONAL BEAUTY SYSTEM</span><div><i/><i/><i/><i/></div></div><div><span>{home.passportEyebrow}</span><h2>{home.passportTitle}</h2>{home.passportDescription?<p>{home.passportDescription}</p>:null}<a href={home.passportButtonLink} className="luxury-button dark">{home.passportButtonText}</a></div></section>:null}
  </main>;
}
