import { prisma } from "@/lib/prisma";
import { createDiscountCode, deleteDiscountCode, updateDiscountCode } from "./actions";

export const dynamic = "force-dynamic";
const formatPrice = (value: number) => new Intl.NumberFormat("fa-IR").format(value);
const dateValue = (date: Date | null) => date ? new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16) : "";

export default async function DiscountsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const query = await searchParams;
  const [codes, products, categories] = await Promise.all([
    prisma.discountCode.findMany({ include: { product: true, category: true, _count: { select: { usages: true } } }, orderBy: { createdAt: "desc" } }),
    prisma.product.findMany({ where: { status: "ACTIVE" }, select: { id: true, title: true }, orderBy: { title: "asc" } }),
    prisma.category.findMany({ select: { id: true, title: true }, orderBy: { title: "asc" } })
  ]);
  const error = query.error === "duplicate" ? "این کد قبلاً ساخته شده است." : query.error === "used" ? "این کد سابقه استفاده دارد و حذف نمی‌شود؛ آن را غیرفعال کن." : "اطلاعات کد را بررسی کن؛ درصد باید بین ۱ تا ۱۰۰ باشد و فقط یک محدودیت محصول یا دسته انتخاب شود.";

  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">ابزار افزایش فروش</p><h1>کدهای تخفیف</h1><p>برای کمپین‌ها کد بساز، زمان و ظرفیت تعیین کن و مصرف هر کد را ببین.</p></div></header>
    <section className="admin-help-note"><strong>از کجا شروع کنم؟</strong><p>برای اولین خرید یک کد درصدی مثل WELCOME10 بساز. حداقل خرید مانع تخفیف روی سفارش‌های خیلی کوچک می‌شود و سقف تخفیف هزینه کمپین را کنترل می‌کند.</p></section>
    {query.success ? <div className="admin-alert success">کد تخفیف با موفقیت ذخیره شد.</div> : null}{query.error ? <div className="admin-alert error">{error}</div> : null}
    <div className="discount-admin-layout"><section className="discount-create"><div className="admin-form-heading"><span>%</span><div><h2>ساخت کد جدید</h2><p>فیلدهای ضروری را پر کن؛ بقیه اختیاری‌اند.</p></div></div><DiscountForm products={products} categories={categories} action={createDiscountCode} submitLabel="ساخت کد تخفیف" /></section>
      <section className="discount-code-list"><div className="admin-table-head"><span>کدهای ساخته‌شده</span><small>{codes.filter((code) => code.active).length} کد فعال</small></div>{codes.length ? codes.map((code) => <article key={code.id}><header><div><span className={`admin-status ${code.active ? "active" : "archived"}`}>{code.active ? "فعال" : "غیرفعال"}</span><strong dir="ltr">{code.code}</strong></div><small>{code._count.usages} بار استفاده</small></header><div className="discount-code-summary"><b>{code.title}</b><span>{code.type === "PERCENT" ? `${formatPrice(code.value)}٪` : `${formatPrice(code.value)} تومان`}</span><small>{code.product?.title || code.category?.title || "تمام محصولات"}</small></div><details><summary>ویرایش تنظیمات</summary><DiscountForm products={products} categories={categories} code={code} action={updateDiscountCode.bind(null, code.id)} submitLabel="ذخیره تغییرات" /></details>{code._count.usages === 0 ? <form action={deleteDiscountCode} className="discount-delete"><input type="hidden" name="id" value={code.id} /><button type="submit">حذف کد</button></form> : null}</article>) : <div className="admin-empty"><strong>هنوز کد تخفیفی ساخته نشده است.</strong><p>فرم روبه‌رو را کامل کن تا اولین کد آماده شود.</p></div>}</section></div>
  </main>;
}

type FormCode = { code: string; title: string; type: "PERCENT" | "FIXED"; value: number; minimumSubtotal: number; maximumDiscount: number | null; usageLimit: number | null; perCustomerLimit: number; startsAt: Date | null; expiresAt: Date | null; productId: string | null; categoryId: string | null; active: boolean };
function DiscountForm({ products, categories, code, action, submitLabel }: { products: { id: string; title: string }[]; categories: { id: string; title: string }[]; code?: FormCode; action: (formData: FormData) => void | Promise<void>; submitLabel: string }) {
  return <form action={action} className="admin-product-form discount-form"><div className="admin-form-grid"><label>کد قابل واردکردن<input name="code" dir="ltr" required defaultValue={code?.code} placeholder="WELCOME10" /></label><label>عنوان داخلی<input name="title" required defaultValue={code?.title} placeholder="تخفیف اولین خرید" /></label><label>نوع تخفیف<select name="type" defaultValue={code?.type || "PERCENT"}><option value="PERCENT">درصدی</option><option value="FIXED">مبلغ ثابت</option></select></label><label>مقدار<input name="value" type="number" min="1" max={code?.type === "PERCENT" ? 100 : undefined} required defaultValue={code?.value || 10} /></label><label>حداقل مبلغ سفارش<input name="minimumSubtotal" type="number" min="0" defaultValue={code?.minimumSubtotal || 0} /></label><label>سقف تخفیف درصدی<input name="maximumDiscount" type="number" min="0" defaultValue={code?.maximumDiscount || ""} placeholder="اختیاری" /></label><label>ظرفیت کل استفاده<input name="usageLimit" type="number" min="1" defaultValue={code?.usageLimit || ""} placeholder="نامحدود" /></label><label>سقف هر مشتری<input name="perCustomerLimit" type="number" min="1" defaultValue={code?.perCustomerLimit || 1} /></label><label>شروع استفاده<input name="startsAt" type="datetime-local" defaultValue={dateValue(code?.startsAt || null)} /></label><label>پایان استفاده<input name="expiresAt" type="datetime-local" defaultValue={dateValue(code?.expiresAt || null)} /></label><label>فقط برای محصول<select name="productId" defaultValue={code?.productId || ""}><option value="">همه محصولات</option>{products.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>یا فقط برای دسته<select name="categoryId" defaultValue={code?.categoryId || ""}><option value="">همه دسته‌ها</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label></div><label className="payment-active"><input name="active" type="checkbox" defaultChecked={code?.active ?? true} /> کد فعال و قابل استفاده باشد</label><button type="submit" className="primary-action">{submitLabel}</button></form>;
}
