CREATE TABLE "HomePageSettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "heroEnabled" BOOLEAN NOT NULL DEFAULT true,
    "heroVideoUrl" TEXT,
    "heroPosterUrl" TEXT,
    "heroEyebrow" TEXT NOT NULL DEFAULT 'BeautyOS Edit',
    "heroTitle" TEXT NOT NULL DEFAULT 'زیبایی، با انتخابی که شبیه توست.',
    "heroDescription" TEXT,
    "heroButtonText" TEXT NOT NULL DEFAULT 'کشف محصولات',
    "heroButtonLink" TEXT NOT NULL DEFAULT '/products',
    "heroSecondaryText" TEXT,
    "heroSecondaryLink" TEXT,
    "postersEnabled" BOOLEAN NOT NULL DEFAULT true,
    "posterOneImageUrl" TEXT,
    "posterOneKicker" TEXT,
    "posterOneTitle" TEXT NOT NULL DEFAULT 'آیین مراقبت روزانه',
    "posterOneDescription" TEXT,
    "posterOneButtonText" TEXT NOT NULL DEFAULT 'مشاهده روتین',
    "posterOneLink" TEXT NOT NULL DEFAULT '/routine',
    "posterTwoImageUrl" TEXT,
    "posterTwoKicker" TEXT,
    "posterTwoTitle" TEXT NOT NULL DEFAULT 'انتخاب دقیق برای پوست تو',
    "posterTwoDescription" TEXT,
    "posterTwoButtonText" TEXT NOT NULL DEFAULT 'ساخت پاسپورت',
    "posterTwoLink" TEXT NOT NULL DEFAULT '/passport',
    "newProductsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "newProductsTitle" TEXT NOT NULL DEFAULT 'تازه‌رسیده‌ها',
    "newProductsDescription" TEXT,
    "bestSellersEnabled" BOOLEAN NOT NULL DEFAULT true,
    "bestSellersTitle" TEXT NOT NULL DEFAULT 'محبوب‌ترین انتخاب‌ها',
    "bestSellersDescription" TEXT,
    "needsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "needsTitle" TEXT NOT NULL DEFAULT 'از نیاز پوستت شروع کن',
    "needsDescription" TEXT,
    "passportEnabled" BOOLEAN NOT NULL DEFAULT true,
    "passportEyebrow" TEXT NOT NULL DEFAULT 'Beauty Passport',
    "passportTitle" TEXT NOT NULL DEFAULT 'فروشگاه باید تو را بشناسد.',
    "passportDescription" TEXT,
    "passportButtonText" TEXT NOT NULL DEFAULT 'ساخت پاسپورت زیبایی',
    "passportButtonLink" TEXT NOT NULL DEFAULT '/passport',
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HomePageSettings_pkey" PRIMARY KEY ("id")
);
