import { getHeaderSettings } from "@/lib/header-settings";
import { getStoreSettings } from "@/lib/store-settings";
import { saveHeaderSettings } from "./actions";

export const dynamic = "force-dynamic";

export default async function HeaderAdmin({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [header, store, query] = await Promise.all([getHeaderSettings(), getStoreSettings(), searchParams]);
  const rows = Array.from({ length: 6 }, (_, index) => header.navItems[index] || { label: "", href: "", active: true });
  return <main className="admin-page narrow">
    <header className="admin-page-header"><div><p className="admin-kicker">ظاهر عمومی فروشگاه</p><h1>هدر، لوگو و فوتر</h1><p>هر چیزی که مشتری در بالا و پایین سایت می‌بیند از همین صفحه مدیریت کن.</p></div><a href="/" className="secondary-action">مشاهده سایت</a></header>
    <section className="admin-help-note"><strong>راهنمای ساده</strong><p>ابتدا هویت و لوگو را تنظیم کن، سپس لینک‌های نوبار و در پایان اطلاعات فوتر را کامل کن. فیلدهای خالی شبکه‌های اجتماعی در سایت نمایش داده نمی‌شوند.</p></section>
    {query.success ? <div className="admin-alert success">هدر، لوگو و فوتر منتشر شدند.</div> : null}
    {query.error ? <div className="admin-alert error">اطلاعات ضروری یا آدرس لینک‌ها درست نیست. لینک داخلی باید با / و لینک خارجی با https:// شروع شود.</div> : null}
    <form action={saveHeaderSettings} className="admin-product-form header-admin-form">
      <section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>هویت و لوگوی فروشگاه</h2><p>نام، جمله کوتاه و لوگوی نمایش‌داده‌شده در هدر را مشخص کن.</p></div></div><div className="admin-form-grid"><label>نام فروشگاه<input name="storeName" required minLength={2} defaultValue={store.storeName} placeholder="BeautyOS" /></label><label>جمله کوتاه برند<input name="tagline" required minLength={3} defaultValue={store.tagline} placeholder="انتخاب زیبایی، براساس خودت" /></label><label className="field-wide">آدرس لوگو <small>PNG شفاف یا SVG پیشنهاد می‌شود</small><input name="logoUrl" dir="ltr" defaultValue={store.logoUrl || ""} placeholder="/uploads/logo.png یا https://..." /><small>ابتدا لوگو را در کتابخانه رسانه آپلود کن و آدرس آن را اینجا قرار بده.</small></label></div><div className="store-brand-preview"><span>{store.logoUrl ? <img src={store.logoUrl} alt="پیش‌نمایش لوگو" /> : store.storeName.charAt(0).toUpperCase()}</span><p><strong>{store.storeName}</strong><small>{store.tagline}</small></p></div><div className="admin-form-actions"><a href="/admin/media" className="secondary-action">آپلود لوگو در کتابخانه رسانه</a></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>نوار تبلیغاتی بالای سایت</h2><p>برای ارسال رایگان، تخفیف یا اطلاعیه کوتاه استفاده کن.</p></div></div><label className="payment-active"><input type="checkbox" name="announcementActive" defaultChecked={header.announcementActive}/><span><strong>نوار تبلیغاتی نمایش داده شود</strong><small>با خاموش‌کردن، هدر اصلی به بالای صفحه می‌رود.</small></span></label><div className="admin-form-grid"><label className="field-wide">متن تبلیغ<input name="announcementText" required defaultValue={header.announcementText}/></label><label>متن لینک<input name="announcementLinkText" defaultValue={header.announcementLinkText || ""} placeholder="خرید کنید"/></label><label>آدرس لینک<input name="announcementLink" dir="ltr" defaultValue={header.announcementLink || ""} placeholder="/products"/></label><label>رنگ پس‌زمینه<input name="announcementBackground" type="color" defaultValue={header.announcementBackground}/><small>{header.announcementBackground}</small></label><label>رنگ نوشته<input name="announcementColor" type="color" defaultValue={header.announcementColor}/><small>{header.announcementColor}</small></label></div><div className="announcement-admin-preview" style={{ background: header.announcementBackground, color: header.announcementColor }}>{header.announcementText}<span>{header.announcementLinkText}</span></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۳</span><div><h2>آیتم‌های وسط نوبار</h2><p>ترتیب ردیف‌ها همان ترتیب نمایش از راست به چپ است. ردیف خالی نمایش داده نمی‌شود.</p></div></div><div className="nav-admin-rows">{rows.map((item, index) => <article key={index}><b>{new Intl.NumberFormat("fa-IR").format(index + 1)}</b><label>عنوان<input name={`navLabel${index}`} defaultValue={item.label} placeholder="مثلاً فروشگاه"/></label><label>لینک<input name={`navHref${index}`} dir="ltr" defaultValue={item.href} placeholder="/products"/></label><label className="nav-active"><input type="checkbox" name={`navActive${index}`} defaultChecked={item.active}/> فعال</label></article>)}</div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۴</span><div><h2>اطلاعات تماس فوتر</h2><p>راه‌های واقعی پشتیبانی را وارد کن تا مشتری برای پیگیری سفارش سردرگم نشود.</p></div></div><div className="admin-form-grid"><label>شماره پشتیبانی<input name="supportPhone" dir="ltr" inputMode="tel" defaultValue={store.supportPhone || ""} placeholder="02112345678" /></label><label>ایمیل پشتیبانی<input name="supportEmail" dir="ltr" type="email" defaultValue={store.supportEmail || ""} placeholder="support@example.com" /></label><label>ساعات پاسخ‌گویی<input name="supportHours" defaultValue={store.supportHours || ""} placeholder="شنبه تا پنجشنبه، ۹ تا ۱۸" /></label><label className="field-wide">آدرس<textarea name="address" rows={3} defaultValue={store.address || ""} placeholder="استان، شهر، خیابان و پلاک" /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۵</span><div><h2>شبکه‌های اجتماعی فوتر</h2><p>لینک کامل صفحه رسمی را وارد کن؛ فیلد خالی نمایش داده نمی‌شود.</p></div></div><div className="admin-form-grid three"><label>اینستاگرام<input name="instagramUrl" dir="ltr" defaultValue={store.instagramUrl || ""} placeholder="https://instagram.com/..." /></label><label>تلگرام<input name="telegramUrl" dir="ltr" defaultValue={store.telegramUrl || ""} placeholder="https://t.me/..." /></label><label>واتساپ<input name="whatsappUrl" dir="ltr" defaultValue={store.whatsappUrl || ""} placeholder="https://wa.me/989..." /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۶</span><div><h2>متن‌های فوتر</h2><p>معرفی کوتاه برند و پیام ارسال را برای پایین تمام صفحات بنویس.</p></div></div><div className="admin-form-grid"><label className="field-wide">درباره فروشگاه<textarea name="footerAbout" rows={4} defaultValue={store.footerAbout || ""} placeholder="چرا مشتری باید به فروشگاه اعتماد کند؟" /></label><label className="field-wide">پیام ارسال و تحویل<input name="shippingNotice" defaultValue={store.shippingNotice || ""} placeholder="ارسال به سراسر ایران با بسته‌بندی امن" /></label></div></section>
      <div className="admin-form-actions"><button className="primary-action">ذخیره و انتشار همه تنظیمات</button><a href="/" className="secondary-action">دیدن خروجی سایت</a></div>
    </form>
  </main>;
}
