import { getHeaderSettings } from "@/lib/header-settings";
import { saveHeaderSettings } from "./actions";
export const dynamic="force-dynamic";
export default async function HeaderAdmin({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
  const [settings,query]=await Promise.all([getHeaderSettings(),searchParams]);
  const rows=Array.from({length:6},(_,index)=>settings.navItems[index]||{label:"",href:"",active:true});
  return <main className="admin-page narrow"><header className="admin-page-header"><div><p className="admin-kicker">هدر و دسترسی‌ها</p><h1>مدیریت نوبار</h1><p>نوار تبلیغاتی و لینک‌های وسط منوی سایت را بدون تغییر کد مدیریت کن.</p></div><a href="/" className="secondary-action">مشاهده سایت</a></header>
    <section className="admin-help-note"><strong>کدام بخش‌ها ثابت هستند؟</strong><p>لوگو، جست‌وجو، حساب و سبد برای جلوگیری از خراب‌شدن مسیر خرید ثابت‌اند. آیتم‌های وسط نوبار و تمام مشخصات نوار تبلیغاتی قابل تغییر هستند.</p></section>{query.success?<div className="admin-alert success">تنظیمات نوبار منتشر شد.</div>:null}{query.error?<div className="admin-alert error">متن‌ها و لینک‌ها را بررسی کن. لینک داخلی باید با / و لینک خارجی با https:// شروع شود.</div>:null}
    <form action={saveHeaderSettings} className="admin-product-form header-admin-form"><section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>نوار تبلیغاتی بالای سایت</h2><p>برای ارسال رایگان، تخفیف یا اطلاعیه کوتاه استفاده کن.</p></div></div><label className="payment-active"><input type="checkbox" name="announcementActive" defaultChecked={settings.announcementActive}/><span><strong>نوار تبلیغاتی نمایش داده شود</strong><small>با خاموش‌کردن، هدر اصلی به بالای صفحه می‌رود.</small></span></label><div className="admin-form-grid"><label className="field-wide">متن تبلیغ<input name="announcementText" required defaultValue={settings.announcementText}/></label><label>متن لینک<input name="announcementLinkText" defaultValue={settings.announcementLinkText||""} placeholder="خرید کنید"/></label><label>آدرس لینک<input name="announcementLink" dir="ltr" defaultValue={settings.announcementLink||""} placeholder="/products"/></label><label>رنگ پس‌زمینه<input name="announcementBackground" type="color" defaultValue={settings.announcementBackground}/><small>{settings.announcementBackground}</small></label><label>رنگ نوشته<input name="announcementColor" type="color" defaultValue={settings.announcementColor}/><small>{settings.announcementColor}</small></label></div><div className="announcement-admin-preview" style={{background:settings.announcementBackground,color:settings.announcementColor}}>{settings.announcementText}<span>{settings.announcementLinkText}</span></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>آیتم‌های وسط نوبار</h2><p>ترتیب ردیف‌ها همان ترتیب نمایش از راست به چپ است. ردیف خالی نمایش داده نمی‌شود.</p></div></div><div className="nav-admin-rows">{rows.map((item,index)=><article key={index}><b>{new Intl.NumberFormat("fa-IR").format(index+1)}</b><label>عنوان<input name={`navLabel${index}`} defaultValue={item.label} placeholder="مثلاً فروشگاه"/></label><label>لینک<input name={`navHref${index}`} dir="ltr" defaultValue={item.href} placeholder="/products"/></label><label className="nav-active"><input type="checkbox" name={`navActive${index}`} defaultChecked={item.active}/> فعال</label></article>)}</div></section><div className="admin-form-actions"><button className="primary-action">ذخیره و انتشار نوبار</button></div></form>
  </main>;
}
