import Image from "next/image";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireCustomer } from "@/lib/auth";
import { createVerifiedReview } from "./actions";

export const dynamic = "force-dynamic";
const skinTypes = [["OILY","چرب"],["DRY","خشک"],["COMBINATION","مختلط"],["NORMAL","نرمال"],["SENSITIVE","حساس"]];

export default async function NewReviewPage({ searchParams }: { searchParams: Promise<{ orderItem?: string; error?: string }> }) {
  const user = await requireCustomer(); const query = await searchParams;
  const item = query.orderItem ? await prisma.orderItem.findFirst({ where: { id: query.orderItem, order: { userId: user.id, status: "DELIVERED" }, review: null }, include: { product: { include: { brand: true, media: { take: 1, orderBy: { sortOrder: "asc" } } } } } }) : null;
  if (!item) notFound(); const image = item.product.media[0];
  return <main className="home-shell review-create-page"><section className="compact-hero results-header"><div className="hero-content"><p className="eyebrow">تجربه خرید تأییدشده</p><h1>تجربه واقعی تو کمک می‌کند.</h1><p className="hero-copy">جواب‌ها باعث می‌شوند افراد با پوست مشابه انتخاب دقیق‌تری داشته باشند.</p></div></section>{query.error ? <div className="cart-message error">عنوان، توضیح و نوع پوست را کامل کن. متن تجربه حداقل ۱۵ حرف باشد.</div> : null}<div className="review-create-layout"><aside>{image ? <Image src={image.url} alt={item.product.title} width={280} height={280} /> : <span /> }<p>{item.product.brand.name}</p><h2>{item.product.title}</h2><small>این نظر با نشان خرید تأییدشده نمایش داده می‌شود.</small></aside><form action={createVerifiedReview} className="review-form"><input type="hidden" name="orderItemId" value={item.id} /><section><h2>امتیاز و نوع پوست</h2><div className="review-form-grid"><label>امتیاز<select name="rating" defaultValue="5">{[5,4,3,2,1].map((value) => <option key={value} value={value}>{value} از ۵</option>)}</select></label><label>نوع پوست<select name="skinType" required defaultValue=""><option value="" disabled>انتخاب کن</option>{skinTypes.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>مدت استفاده (روز)<input name="daysUsed" type="number" min="1" max="3650" defaultValue="14" /></label></div></section><section><h2>نتیجه استفاده</h2><div className="review-question-grid"><label>باعث تحریک یا حساسیت شد؟<select name="irritation" defaultValue="no"><option value="no">خیر</option><option value="yes">بله</option></select></label><label>به دغدغه پوستت کمک کرد؟<select name="helpedConcern" defaultValue="yes"><option value="yes">بله</option><option value="no">خیر</option></select></label><label>دوباره می‌خری؟<select name="wouldRepurchase" defaultValue="yes"><option value="yes">بله</option><option value="no">خیر</option></select></label></div></section><section><h2>تجربه‌ات را بنویس</h2><label>عنوان کوتاه<input name="title" required minLength={3} placeholder="مثلاً برای پوست خشک من عالی بود" /></label><label>توضیح کامل<textarea name="body" required minLength={15} rows={5} placeholder="بافت، نتیجه، حساسیت و تجربه مصرفت را بنویس..." /></label><label>خلاصه نتیجه <small>اختیاری</small><input name="outcomeSummary" placeholder="مثلاً بعد از دو هفته خشکی کمتر شد" /></label></section><div className="review-submit-note">نظر ابتدا توسط مدیر بررسی می‌شود و سپس در صفحه محصول منتشر خواهد شد.</div><button type="submit" className="primary-action">ارسال تجربه برای بررسی</button></form></div></main>;
}
