import { prisma } from "@/lib/prisma";
import { deleteMedia, uploadMedia } from "./actions";
import { CopyMediaUrl } from "./media-tools";
export const dynamic = "force-dynamic";
const size = (bytes:number) => bytes >= 1024*1024 ? `${new Intl.NumberFormat("fa-IR",{maximumFractionDigits:1}).format(bytes/1024/1024)} مگابایت` : `${new Intl.NumberFormat("fa-IR").format(Math.ceil(bytes/1024))} کیلوبایت`;

export default async function MediaPage({ searchParams }: { searchParams: Promise<{ type?:string; success?:string; error?:string }> }) {
  const query = await searchParams;
  const assets = await prisma.mediaAsset.findMany({ where: query.type === "image" ? {kind:"IMAGE"} : query.type === "video" ? {kind:"VIDEO"} : {}, orderBy:{createdAt:"desc"} });
  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">فایل‌های فروشگاه</p><h1>کتابخانه رسانه</h1><p>تصویر و ویدیو را یک‌بار آپلود کن و در صفحه اصلی، لوگو یا بخش‌های دیگر استفاده کن.</p></div><a href="/admin/homepage" className="secondary-action">مدیریت صفحه اصلی</a></header>
    <section className="admin-help-note"><strong>چه فایلی مناسب است؟</strong><p>تصاویر JPG، PNG، WebP یا AVIF تا ۸ مگابایت؛ ویدیو MP4 یا WebM تا ۳۰ مگابایت. برای بنر اصلی ویدیو افقی ۱۶:۹ پیشنهاد می‌شود.</p></section>
    {query.success ? <div className="admin-alert success">{query.success === "deleted" ? "فایل حذف شد." : "فایل با موفقیت آپلود شد."}</div> : null}{query.error ? <div className="admin-alert error">{query.error === "used" ? "این فایل در سایت استفاده شده است؛ ابتدا آن را از بخش مربوطه بردار." : query.error === "size" ? "حجم فایل بیشتر از حد مجاز است." : query.error === "type" ? "فرمت فایل پشتیبانی نمی‌شود." : "فایل معتبر انتخاب کن."}</div> : null}
    <section className="media-admin-layout"><form action={uploadMedia} className="media-uploader"><div><span>＋</span><h2>آپلود فایل جدید</h2><p>فایل از کامپیوترت انتخاب کن.</p></div><label className="admin-upload-zone"><span>انتخاب تصویر یا ویدیو</span><input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" required /><small>تصویر حداکثر ۸MB · ویدیو حداکثر ۳۰MB</small></label><label>متن جایگزین تصویر <small>برای سئو و دسترسی‌پذیری</small><input name="alt" placeholder="مثلاً سرم مراقبت پوست روی زمینه روشن" /></label><button className="primary-action">آپلود در کتابخانه</button></form><div className="media-library"><nav><span>{new Intl.NumberFormat("fa-IR").format(assets.length)} فایل</span><div><a className={!query.type ? "active":""} href="/admin/media">همه</a><a className={query.type === "image" ? "active":""} href="/admin/media?type=image">تصاویر</a><a className={query.type === "video" ? "active":""} href="/admin/media?type=video">ویدیوها</a></div></nav>{assets.length ? <div className="media-grid">{assets.map((asset)=><article key={asset.id}><div className="media-preview">{asset.kind === "VIDEO" ? <video src={asset.url} controls preload="metadata" /> : <img src={asset.url} alt={asset.alt || asset.originalName} /> }<span>{asset.kind === "VIDEO" ? "ویدیو" : "تصویر"}</span></div><div className="media-meta"><strong title={asset.originalName}>{asset.originalName}</strong><small>{size(asset.sizeBytes)} · {new Intl.DateTimeFormat("fa-IR").format(asset.createdAt)}</small><code dir="ltr">{asset.url}</code><div><CopyMediaUrl url={asset.url}/><form action={deleteMedia}><input type="hidden" name="id" value={asset.id}/><button className="delete">حذف</button></form></div></div></article>)}</div> : <div className="admin-empty"><strong>کتابخانه خالی است.</strong><p>اولین تصویر یا ویدیو را از فرم کناری آپلود کن.</p></div>}</div></section>
  </main>;
}
