import { getStoreSettings } from "@/lib/store-settings";
import { saveStoreSettings } from "./actions";

export const dynamic = "force-dynamic";

export default async function StoreSettingsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const [settings, query] = await Promise.all([getStoreSettings(), searchParams]);
  return <main className="admin-page narrow">
    <header className="admin-page-header"><div><p className="admin-kicker">ظاهر و اطلاعات عمومی</p><h1>تنظیمات فروشگاه</h1><p>اطلاعاتی را مدیریت کن که مشتری در بالای سایت، فوتر و راه‌های ارتباطی می‌بیند.</p></div><a href="/" className="secondary-action">مشاهده فروشگاه</a></header>
    <section className="admin-help-note"><strong>فرق این صفحه با سئو چیست؟</strong><p>اینجا ظاهر و اطلاعات قابل مشاهده مشتری را تغییر می‌دهی. عنوان و توضیحات گوگل همچنان از بخش «سئو و گوگل» مدیریت می‌شود.</p></section>
    {query.success ? <div className="admin-alert success">تنظیمات ذخیره شد و در هدر و فوتر فروشگاه نمایش داده می‌شود.</div> : null}
    {query.error ? <div className="admin-alert error">{query.error === "url" ? "آدرس لینک باید با https:// یا / شروع شود." : "نام فروشگاه و توضیح کوتاه را کامل وارد کن."}</div> : null}
    <form action={saveStoreSettings} className="admin-product-form store-settings-form">
      <section className="admin-form-section"><div className="admin-form-heading"><span>۱</span><div><h2>هویت فروشگاه</h2><p>این نام و جمله کنار لوگو در بالای همه صفحات دیده می‌شوند.</p></div></div><div className="admin-form-grid"><label>نام فروشگاه<input name="storeName" required minLength={2} defaultValue={settings.storeName} placeholder="BeautyOS" /></label><label>جمله کوتاه برند<input name="tagline" required minLength={3} defaultValue={settings.tagline} placeholder="انتخاب زیبایی، براساس خودت" /></label><label className="field-wide">آدرس لوگو <small>اختیاری</small><input name="logoUrl" dir="ltr" defaultValue={settings.logoUrl || ""} placeholder="/logo.svg یا https://..." /><small>اگر خالی باشد، نشان حرف اول نام فروشگاه نمایش داده می‌شود.</small></label></div><div className="store-brand-preview"><span>{settings.logoUrl ? <img src={settings.logoUrl} alt="پیش‌نمایش لوگو" /> : settings.storeName.charAt(0).toUpperCase()}</span><p><strong>{settings.storeName}</strong><small>{settings.tagline}</small></p></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۲</span><div><h2>پشتیبانی و آدرس</h2><p>اطلاعات واقعی وارد کن تا مشتری برای پیگیری سفارش سردرگم نشود.</p></div></div><div className="admin-form-grid"><label>شماره پشتیبانی<input name="supportPhone" dir="ltr" inputMode="tel" defaultValue={settings.supportPhone || ""} placeholder="02112345678" /></label><label>ایمیل پشتیبانی<input name="supportEmail" dir="ltr" type="email" defaultValue={settings.supportEmail || ""} placeholder="support@example.com" /></label><label>ساعات پاسخ‌گویی<input name="supportHours" defaultValue={settings.supportHours || ""} placeholder="شنبه تا پنجشنبه، ۹ تا ۱۸" /></label><label className="field-wide">آدرس<textarea name="address" rows={3} defaultValue={settings.address || ""} placeholder="استان، شهر، خیابان و پلاک" /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۳</span><div><h2>شبکه‌های اجتماعی</h2><p>لینک کامل صفحه رسمی را وارد کن؛ فیلد خالی در فوتر نمایش داده نمی‌شود.</p></div></div><div className="admin-form-grid three"><label>اینستاگرام<input name="instagramUrl" dir="ltr" defaultValue={settings.instagramUrl || ""} placeholder="https://instagram.com/..." /></label><label>تلگرام<input name="telegramUrl" dir="ltr" defaultValue={settings.telegramUrl || ""} placeholder="https://t.me/..." /></label><label>واتساپ<input name="whatsappUrl" dir="ltr" defaultValue={settings.whatsappUrl || ""} placeholder="https://wa.me/989..." /></label></div></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۴</span><div><h2>نوار اطلاع‌رسانی</h2><p>برای ارسال رایگان، تخفیف یا اطلاعیه مهم در بالای سایت استفاده کن.</p></div></div><div className="admin-form-grid"><label className="field-wide">متن اطلاعیه<input name="announcementText" defaultValue={settings.announcementText || ""} placeholder="ارسال رایگان برای خریدهای بالای ..." /></label><label className="field-wide">لینک اطلاعیه <small>اختیاری</small><input name="announcementLink" dir="ltr" defaultValue={settings.announcementLink || ""} placeholder="/products یا https://..." /></label></div><label className="payment-active"><input type="checkbox" name="announcementActive" defaultChecked={settings.announcementActive} /><span><strong>نوار اطلاع‌رسانی فعال باشد</strong><small>اگر متن خالی باشد چیزی نمایش داده نمی‌شود.</small></span></label></section>
      <section className="admin-form-section"><div className="admin-form-heading"><span>۵</span><div><h2>محتوای فوتر</h2><p>خلاصه‌ای کوتاه از فروشگاه و یک پیام مهم درباره ارسال بنویس.</p></div></div><div className="admin-form-grid"><label className="field-wide">درباره فروشگاه<textarea name="footerAbout" rows={4} defaultValue={settings.footerAbout || ""} placeholder="چرا مشتری باید به این فروشگاه اعتماد کند؟" /></label><label className="field-wide">پیام ارسال و تحویل<input name="shippingNotice" defaultValue={settings.shippingNotice || ""} placeholder="ارسال به سراسر ایران با بسته‌بندی امن" /></label></div></section>
      <div className="admin-form-actions"><button type="submit" className="primary-action">ذخیره و انتشار تنظیمات</button><a href="/" className="secondary-action">دیدن خروجی سایت</a></div>
    </form>
  </main>;
}
