import { prisma } from "@/lib/prisma";
import { moderateReview } from "./actions";

export const dynamic = "force-dynamic";
const skinLabels: Record<string,string> = { OILY:"چرب", DRY:"خشک", COMBINATION:"مختلط", NORMAL:"نرمال", SENSITIVE:"حساس", UNKNOWN:"نامشخص" };
const statusLabels: Record<string,string> = { PENDING:"در انتظار بررسی", APPROVED:"منتشرشده", REJECTED:"ردشده" };

export default async function AdminReviewsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const query = await searchParams;
  const reviews = await prisma.review.findMany({ where: { source: { not: "IMPORTED" } }, include: { product: true, user: true, outcome: true }, orderBy: [{ status: "asc" }, { createdAt: "desc" }] });
  return <main className="admin-page"><header className="admin-page-header"><div><p className="admin-kicker">اعتماد و تجربه مشتری</p><h1>مدیریت نظرات</h1><p>نظر خریدار واقعی را بررسی کن؛ متن سالم را منتشر و در صورت نیاز پاسخ رسمی ثبت کن.</p></div></header><section className="admin-help-note"><strong>چه نظری تأیید شود؟</strong><p>تجربه واقعی حتی اگر منفی باشد باید منتشر شود. فقط توهین، اطلاعات شخصی، تبلیغ یا متن نامرتبط را رد کن.</p></section>{query.success ? <div className="admin-alert success">وضعیت نظر با موفقیت تغییر کرد.</div> : null}{query.error ? <div className="admin-alert error">بررسی نظر انجام نشد.</div> : null}<section className="admin-review-list">{reviews.length ? reviews.map((review) => <article key={review.id}><header><div><span className={`review-admin-status ${review.status.toLowerCase()}`}>{statusLabels[review.status]}</span><strong>{review.product.title}</strong></div><span>{"★".repeat(review.rating)} · پوست {skinLabels[review.skinTypeAtReview]}</span></header><div className="admin-review-content"><h2>{review.title || "تجربه استفاده"}</h2><p>{review.body}</p><div><span>خرید تأییدشده</span>{review.outcome?.daysUsed ? <span>{review.outcome.daysUsed} روز استفاده</span> : null}<span>{review.outcome?.irritation ? "تحریک ایجاد کرده" : "بدون تحریک گزارش‌شده"}</span><span>{review.wouldRepurchase ? "دوباره می‌خرد" : "دوباره نمی‌خرد"}</span></div></div><footer><form action={moderateReview}><input type="hidden" name="reviewId" value={review.id} /><label>پاسخ مدیر <small>اختیاری</small><input name="adminReply" defaultValue={review.adminReply || ""} placeholder="پاسخ رسمی فروشگاه" /></label><div><button name="decision" value="reject" className="receipt-reject">رد نظر</button><button name="decision" value="approve" className="receipt-approve">تأیید و انتشار</button></div></form></footer></article>) : <div className="admin-empty"><strong>هنوز نظر مشتری برای بررسی وجود ندارد.</strong><p>بعد از تحویل سفارش، مشتری می‌تواند تجربه محصول را ثبت کند.</p></div>}</section></main>;
}
